### ISSUE TITLE
Ubuntu 16.04 package?

### ISSUE THREAD

**Issue by zachleigh** [mroonga/mroonga#106]
Is an Ubuntu 16.04 package going to be released on the PPA? If so, when do you think it will be in the repo?

**Comment by cosmo0920** [comment]
Currently, there is no package for Ubuntu 16.04.
We plan to provide Ubuntu 16.04 package in Mroonga 6.02.
Mroonga 6.02 will be released in 4/29.

**Comment by zachleigh** [comment]
Ok. Thanks! looking forward to it!

**Comment by zachleigh** [comment]
Any idea when it will be in the 16.04 ppa?

**Comment by kou** [comment]
Sorry. I've uploaded.

**Comment by zachleigh** [comment]
No problem, kou. Thanks!
