### ISSUE TITLE
compiled but can't install plugin

### ISSUE THREAD

**Issue by OtisLin** [mroonga/mroonga#112]
I compile Mroonga 6.07 on Amazon AMI with groonga-6.0.7, and got error when I try to install plugin to mysql 5.5.49:

mysql> INSTALL PLUGIN Mroonga SONAME 'ha_mroonga.so';
ERROR 1126 (HY000): Can't open shared library '/usr/lib64/mysql/plugin/ha_mroonga.so' (errno: 2 /usr/lib64/mysql/plugin/ha_mroonga.so: undefined symbol: my_pthread_fastmutex_init)

**Comment by kenhys** [comment]
How about configure with `--disable-fast-mutexes` option to build Mroonga?

**Comment by OtisLin** [comment]
It works.

Thank you very much.
