### ISSUE TITLE
AmazonLinuxでインストールが失敗する

### ISSUE THREAD

**Issue by kazuemasaki** [mroonga/mroonga#127]
初めまして。現在Mroongaのインストールでハマっておりまして、無知で申し訳ありませんが、ご助言いただけないでしょうか。

OSはAmazonLinuxです。
[CentOS 6（OracleのMySQL 5.6パッケージを利用）](http://mroonga.org/ja/docs/install/centos.html#centos-6-with-the-oracle-mysql-5-6-package) の手順で進めていたのですが、
`sudo yum install -y mysql-community-mroonga`
上記コマンドの結果が以下のようにエラーになります。

```(略)
エラー: パッケージ: groonga-libs-6.1.5-1.el6.x86_64 (groonga)
             要求: libzstd
エラー: パッケージ: groonga-libs-6.1.5-1.el6.x86_64 (groonga)
             要求: libzstd.so.1()(64bit)
エラー: パッケージ: groonga-libs-6.1.5-1.el6.x86_64 (groonga)
             要求: libmsgpackc.so.2()(64bit)`
```

**Comment by kou** [comment]
以下を試してみてもらえますか？

```text
% sudo yum install -y --enablerepo=epel mysql-community-mroonga
```

**Comment by kazuemasaki** [comment]
インストールできました！([インストールチェック](http://mroonga.org/ja/docs/tutorial/installation_check.html)に成功しました。)

すぐにご回答いただき非常に助かりました！ありがとうございました！

**Comment by kou** [comment]
それはよかったです！

まわりの人にもMroongaを進めていってください！
