### ISSUE TITLE
debian mariadb-server-10.0に対するDependsがおかしい

### ISSUE THREAD

**Issue by kenji-nishii** [mroonga/mroonga#129]
OS debian
apt-cache showpkg mariadb-server-10.0-mroonga

```
6.13-2 - libc6 (2 2.14) libgcc1 (2 1:4.1.1) libgroonga0 (2 5.1.0) libstdc++6 (2 4.1.1) mariadb-server-10.0 (5 10.0.28-0+deb8u1) mariadb
-server-core-10.0 (5 10.0.28-0+deb8u1) groonga-normalizer-mysql (0 (null)) mariadb-plugin-mroonga (0 (null))
6.13-1 - libc6 (2 2.14) libgcc1 (2 1:4.1.1) libgroonga0 (2 5.1.0) libstdc++6 (2 4.1.1) mariadb-server-10.0 (5 10.0.28-0+deb8u1) mariadb
-server-core-10.0 (5 10.0.28-0+deb8u1) groonga-normalizer-mysql (0 (null)) mariadb-plugin-mroonga (0 (null))
6.11-1 - libc6 (2 2.14) libgcc1 (2 1:4.1.1) libgroonga0 (2 5.1.0) libstdc++6 (2 4.1.1) mariadb-server-10.0 (5 10.0.28-0+deb8u1) mariadb

-server-core-10.0 (5 10.0.28-0+deb8u1) groonga-normalizer-mysql (0 (null)) mariadb-plugin-mroonga (0 (null))
6.10-1 - libc6 (2 2.14) libgcc1 (2 1:4.1.1) libgroonga0 (2 5.1.0) libstdc++6 (2 4.1.1) mariadb-server-10.0 (5 10.0.27-0+deb8u1) mariadb
-server-core-10.0 (5 10.0.27-0+deb8u1) groonga-normalizer-mysql (0 (null)) mariadb-plugin-mroonga (0 (null))
```

6.13-2 を使おうとすると、mariadb-server-10.0 (= 10.0.28-0+deb8u1)と言われるが
mariadb-server-10.0=10.0.28-0+deb8u1 は存在しない。

Dependsを変えて欲しい。。。

**Comment by kou** [comment]
報告ありがとうございます！

mariadb-server-10.0-mroongaが依存するmariadb-server-10.0のバージョンを更新しました。

Mroongaリリース後にDebianのmariadb-server-10.0のバージョンが上がるとこういう状態になるので、今後、また気づいたら教えてもらえると助かります。

**Comment by kenji-nishii** [comment]
おかげでdockerで使えるようになりました！ありがとうございます！
[https://github.com/kenji-nishii/debian-mariadb-mroonga-mecab](https://github.com/kenji-nishii/debian-mariadb-mroonga-mecab)

**Comment by kou** [comment]
おぉ！

↓でMySQL用の公式Dockerサポートを提供しているのですが、それとまとめてMariaDBサポートも提供しませんか！？あるいは別のリポジトリーでもよいのですが、公式サポートできるとうれしい人がいそうだなぁと思いました。

* https://github.com/mroonga/docker
* https://hub.docker.com/r/groonga/mroonga/

公式Dockerサポートとしてメンテナンスしてくれるのであれば権限の設定をします！どうですか！？
