### ISSUE TITLE
Not fixed #130 mysql57 + log-bin causes update statement error

### ISSUE THREAD

**Issue by kitora** [mroonga/mroonga#132]
I checked mroonga7.00 on centos:centos5.8 docker instance, but unfortunately issue #130 remains.
Reproducing process is same.

**Comment by kou** [comment]
Sorry. I didn't care `COLLATE`.

**Comment by kitora** [comment]
Thank you for your rapid fix!
I will check in the next release. ( next NIKU day? )

**Comment by kou** [comment]
Yes. We'll release the next release at 2017-3-29.

**Comment by kitora** [comment]
I confirmed this has been fixed on 7.01. Thank you.

**Comment by kou** [comment]
Thanks for confirming it!
