### ISSUE TITLE
MariaDB-Server 10.0.12 と Mroonga 7.00 のインストール時に、Plugin のインストールに失敗する

### ISSUE THREAD

**Issue by r-fujiwara** [mroonga/mroonga#140]
お世話になっております。
Mroonga のインストール際に下記のような現象が起こりましたので報告させていただきます。

# 概要

-[MariaDB-Galera Cluster 10.0.12](https://mariadb.com/kb/en/mariadb/mariadb-galera-cluster-10012-release-notes/) を利用して、ビルドした `.so` ファイルの install に失敗する

# 環境に関する情報

- MariaDB-Galera に関する情報
  - MariaDB `10.0.12` を利用しております。

```
$ mysql --version 
mysql  Ver 15.1 Distrib 10.0.12-MariaDB, for Linux (x86_64) using readline 5.1

$ mysql -u user
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4578
Server version: 10.0.12-MariaDB-wsrep MariaDB Server, wsrep_25.10.r4002
```

- OS のバージョンに関する情報

```
$ cat /etc/system-release
CentOS release 6.5 (Final)
```

- Groonga のパス

```
$ which groonga
/usr/bin/groonga
```

- Groonga の 周辺ツールのインストール情報

```
$ yum list installed |grep groonga
groonga.x86_64       7.0.2-1.el6        @groonga
groonga-devel.x86_64 7.0.2-1.el6        @groonga
groonga-libs.x86_64  7.0.2-1.el6        @groonga
groonga-normalizer-mysql.x86_64
                     1.1.1-1.el6        @groonga
groonga-plugin-suggest.x86_64
                     7.0.2-1.el6        @groonga
groonga-release.noarch
                     1.3.0-1            @/groonga-release-1.3.0-1.noarch
```

# 再現手順

#### ホームディレクトリに移動

```
$ cd $HOME
```

### mariadb  galera cluster の ソースを以下からダウンロード 

- [mariadb-galera-10.0.12.tar.gz / Source x86](https://downloads.mariadb.org/f/mariadb-galera-10.0.12/source/mariadb-galera-10.0.12.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/?serve)
  - その後 mariadb-galera を解凍
- mroonga のソースをダウンロードして解凍

```
$ https://packages.groonga.org/source/mroonga/mroonga-7.00.tar.gz
$ tar xvzf mroonga-7.00
```
### mroonga のディレクトリに移動して公式ドキュメントにしたがって、configure

```
$ cd mroonga-7.00
$ ./configure --with-mysql-config=/usr/bin/mysql_config --with-mysql-source=$HOME/mariadb-10.0.12 
```

### make をする

```
$ make j=4
```

- ビルドに失敗するので `mariadb-10.0.12/sql/item_cmpfunc.h"` の  29行目 を書き換える 
  - `#include "pcre.h"` => `#include "pcre.h.in"`
    - 以上に書き換える
  - 参考: [MariaDB v10.0.3とMroonga v4.0.5インストール時にmakeでERRORになった話](http://kazukiyunoue-tech.hatenablog.com/entry/2014/09/12/122232)

**before**

```c
  26 #include "thr_malloc.h"                         /* sql_calloc */
  27 #include "item_func.h"             /* Item_int_func, Item_bool_func */
  28 #define PCRE_STATIC 1             /* Important on Windows */
  29 #include "pcre.h"                 /* pcre header file */
  30
```

**after**

```
  26 #include "thr_malloc.h"                         /* sql_calloc */
  27 #include "item_func.h"             /* Item_int_func, Item_bool_func */
  28 #define PCRE_STATIC 1             /* Important on Windows */
  29 #include "pcre.h.in"                 /* pcre header file */
  30
```

### 再度 make をすると、成功する

```
$ make j=4
$ make install 
```

### `.so` ファイルの存在を確認する

```
$ ls /usr/lib64/mysql/plugin/|grep mroonga
ha_mroonga.a
ha_mroonga.la
ha_mroonga.so
ha_mroonga.so.0
ha_mroonga.so.0.0.0
```

### mysql に install を行う

```
$ mysql -u root  <  /usr/local/share/mroonga/install.sql
ERROR 1126 (HY000) at line 3: Can't open shared library 'ha_mroonga.so' (errno: 8, API version for STORAGE ENGINE plugin Mroonga not supported by this version of the server)
```

- **上記のように `.so` ファイルにインストールに失敗する**

# 備考

- もし他に必要なログや確認すべき点がございましたら、何かご助言いただけますでしょうか？

**Comment by r-fujiwara** [comment]
【追記】

`install.sql` を実行時の `mysql` の エラーログを確認しました。

```
$ ps aux|grep mysql 
 /usr/sbin/mysqld --log-error=/var/lib/mysql/log.err
```

```
MariaDB [(none)]> SELECT @@GLOBAL.general_log_file;
+---------------------------+
| @@GLOBAL.general_log_file |
+---------------------------+
| database01.log            |
+---------------------------+

MariaDB [(none)]> SELECT @@GLOBAL.log_warnings;
+-----------------------+
| @@GLOBAL.log_warnings |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set (0.00 sec)
```

しかし、`$ mysql -u root < /usr/local/share/mroonga/install.sql` を実行した際のエラーらしきログは特に確認出来ませんでした。

```
$ cat /var/lib/mysql/database01.err
170509 16:45:16 [Warning] IP address '192.168.10.238' could not be resolved: Name or service not known
170509 17:22:50 [Warning] IP address '192.168.10.216' could not be resolved: Name or service not known
```

**Comment by komainu8** [comment]
1点、教えていただきたいことがあります。
mariadb galera clusterをどのようにインストールしたかを教えていただけないでしょうか？
インストール時に使用したコマンドをオプションを含めて全てご記載いただけると助かります。

mroongaのconfigure実行時に指定している`--with-mysql-config`がmariadbのデフォルトのインストール先ではなかったので、`--with-mysql-config` が正しいパスを指しているのかを確認させていただきたく、上記の質問をさせていただいた次第です。

**Comment by r-fujiwara** [comment]
@komainu8 

ありがとうございます。

インストールしたコマンドは以下になります

```
mariadb galera clusterをどのようにインストールしたかを教えていただけないでしょうか？
インストール時に使用したコマンドをオプションを含めて全てご記載いただけると助かります。
```

```
$ wget https://downloads.mariadb.com/MariaDB/mariadb-10.0.12/yum/rhel6-amd64/rpms/MariaDB-Galera-10.0.12-centos6-x86_64-server.rpm
$ yum localinstall MariaDB-Garela
```

また、再度 `mysql_config` の場所を再度確認いたしました所以下となっておりました。

```
$ which mysql_config
/usr/bin/mysql_config
```

**Comment by komainu8** [comment]
@r-fujiwara 
情報のご提供ありがとうございます。

Mroongaをソースコードからインストールする場合には、MariaDBもソースからビルドする必要があります。
参考URL：http://mroonga.org/ja/docs/install/others.html#mysql

ご提供いただいた、MariaDBのインストール方法を拝見すると、RPMパッケージからインストールされているようですので、一度、ソースからMariaDBをビルドいただいた状態で、Mroongaがインストール出来るかお試しいただけますでしょうか？

※ 上記に記載しました、参考URLでは、MySQL(MariaDB)のビルドとインストールを実施していますが、今回はすでにパッケージからMariaDBをインストールいただいていますので、パッケージインストール時と同じオプションを使ってソースからビルドのみ行い(インストールは行わない)、Mroongaを再度ビルド/インストールするという手順が良いかと思います。
上記の手順とすることで、パッケージでインストールしたMariaDBも使うことができます。

**Comment by kenhys** [comment]
確認手順を案内していますが、その後動きがないのでいったん閉じます。
