### ISSUE TITLE
bigintのカラムで正しくORDER BYが出来ない

### ISSUE THREAD

**Issue by peka2** [mroonga/mroonga#146]
mysql5.7+mroongaエンジンのテーブルでbigintのカラムを使ってORDER BY ASC、DESCをしたとき、
どうもレコード登録順？でソートされていて、bigintの数値を使ったソートになりませんでした。
同カラムをintにALTER TABLEすると、intでは正しくORDER BYが可能でした。

環境
CentOS6
mysql 5.7
mysql57-community-mroonga 7.03

**Comment by kou** [comment]
報告ありがとうございます！

問題が再現した`CREATE TABLE`と`INSERT`と`SELECT`も提供してもらえると助かります！こちらでも再現するか確認します。

**Comment by kenhys** [comment]
その後動きがなさそうなのでいったん閉じる。
