### ISSUE TITLE
Remove deperecated Windows batch files using Visual Studio 2013

### ISSUE THREAD

**Issue by cosmo0920** [mroonga/mroonga#147]
Because Visual Studio 2013 Community cannot build latest MariaDB 10.1.24.
We should also migrate to use Visual Studio 2015 to build and use in document.

**Comment by kou** [comment]
Patch please.

**Comment by cosmo0920** [comment]
Sure, I'll do it.

**Comment by cosmo0920** [comment]
I checked building instruction document for Windows.
It is already updated to use VS2015.
But I found that we still need to remove outdated batch files for VS2013.

I've sent PR #151.
