### ISSUE TITLE
Useless data files after fail to alter table

### ISSUE THREAD

**Issue by whdckszxxx** [mroonga/mroonga#168]
First of all, thanks for great engine.

I tried to change a table's engine to mroonga from innodb.

It was failed because free disk space was not enough to do it.

And after that i noticed my disk usage was increased though the table engine was still innodb!

so I looked into mysql data directory, I found many .mrn. files. I didn't know what those files for, but I deleted them to free my disk space.

I think **Mroonga should delete those files when alter fails.**

**Comment by kou** [comment]
Please show the `.mrn` files by `ls -lah DB_DIR`.

**Comment by kou** [comment]
No feedback.

**Comment by whdckszxxx** [comment]
Sorry for late. I don't have any .mrn files anymore since I removed manually.

**Comment by kou** [comment]
No problem.
If you get the same problem again, please help us.
