### ISSUE TITLE
UDF last_insert_grn_id should be renamed to mroonga_last_insert_grn_id

### ISSUE THREAD

**Issue by iangilfillan** [mroonga/mroonga#177]
last_insert_grn_id() is a UDF that comes with Mroonga. Unlike all the other Mroonga UDFs, it is not prefixed by mroonga_

**Comment by kou** [comment]
I think so too.
We'll add `mroonga_` prefix and make `last_insert_grn_id` deprecated.
We'll remove `last_insert_grn_id` later.

**Comment by kou** [comment]
Done.
