### ISSUE TITLE
TokenMecabのハイフンマイナスの正規化について

### ISSUE THREAD

**Issue by takagi01** [mroonga/mroonga#180]
Mecabで辞書を作成して検索をかけてみたのですが、TokenMecabで
全角のハイフンの正規化についてご相談があります。
いわゆる「全角ハイフンマイナス」という文字はUnicodeでU+FF0Dだそうですが、
こちらについてはTokenMecabできちんと正規化されて半角に変換され、
辞書とのマッチングが成功するのですが、なぜかMacで普通にキーボードから
入力する全角のハイフン文字は「全角マイナス」U+2212とのことで、こちらで
入力された文字は正規化に失敗し、マッチングに失敗します。
mecab-ipadicの方では「負符号」としてハイフンマイナスに変換しているようなのですが、
同じ対応をTokenMecabでも施していただくことは可能でしょうか？
ご検討のほどよろしくお願いいたします。

**Comment by kou** [comment]
mecab-ipadicだと期待する挙動になるというのをどうやって確認したか教えてもらえませんか？

**Comment by takagi01** [comment]
ご返信ありがとうございます。
こんな風にしてみました。
１）私の方でmecabに郵便番号の辞書を作成。３桁目と４桁目の間にハイフンを入れてみました。
２）試しに半角で以下のようなコマンドを叩いてみます。
select mroonga_command('tokenize TokenMecab "100-0000" NormalizerAuto');
→　[{"value":"100-0000","position":0,"force_prefix":false}] 
３）「全角ハイフンマイナス」を適当にコピペして全角でチェック。
select mroonga_command('tokenize TokenMecab "１００﹣００００" NormalizerAuto');
→　[{"value":"100-0000","position":0,"force_prefix":false}]
４）Macで普通に全角のハイフン（「全角マイナス」）をキーボードから入力してチェック
select mroonga_command('tokenize TokenMecab "１００ー００００" NormalizerAuto');
→　[{"value":"100","position":0,"force_prefix":false},{"value":"ー","position":1,"force_prefix":false},{"value":"0000","position":2,"force_prefix":false}] 
よろしくお願いいたします。

**Comment by takagi01** [comment]
あ、そういうお答えではなかったでしょうか？
mecab-ipadicでは
https://github.com/neologd/mecab-ipadic-neologd/wiki/Regexp.ja
こちらのサイトで置換していると書いてありましたので、置換しているんだろうなと認識しただけで
確認はしていません。
よろしくお願いいたします。

**Comment by kou** [comment]
あぁ、mecab-ipadicではなく、mecab-ipadic-neologdの話ですか！

デフォルトで何でもかんでも正規化すればよいというものでもなく、バランスが大事なので難しい話なんですが検討します。あと、ルールを変えると互換性が壊れるのでそこらへんも考慮しないといけないのが難しいところです。

ユーザーがアプリケーションに合わせてルールをカスタマイズできる、という方法も検討していたのでそれもあわせて考えます。

**Comment by takagi01** [comment]
ごめんなさい、こちら別物なんですね。
難しいところ、ご検討ありがとうございます。
取り急ぎ辞書のパターンを増やせば解決するのかなと思っております。
今後ともよろしくお願いいたします。

**Comment by kou** [comment]
ノーマライザーに`NormalizerNFKC121("unify_hyphen_and_prolonged_sound_mark", true)`を指定するとできるようになりました。

参考：

  * http://groonga.org/ja/docs/reference/normalizers/normalizer_nfkc100.html
  * http://mroonga.org/ja/docs/tutorial/storage.html#how-to-specify-the-normalizer
  * https://github.com/mroonga/mroonga/blob/master/mysql-test/mroonga/storage/create/table/index/normalizer/t/comment_options.test
