### ISSUE TITLE
Invalid fast_order_limit was applied to the query includes the subquery

### ISSUE THREAD

**Issue by ashphy** [mroonga/mroonga#184]
The fast_order_limit optimization was applied unexpectedly to the query including subquery.

fast_order_limit 最適化が適用されるべきではないと思われる、サブクエリを含むクエリに最適化が適用されてしまう場合があるようです。

# Reproduce Query
If fast_order_limit optimization is enabled on the query including subquery, `LIMIT` is applied to `MATCH AGAINST`, then the search filter will be applied by that result.

In this case, I think it should not be enabled fast_order_limit optimization.

以下のようにサブクエリがあるクエリに対してfast_order_limit最適化を行ってしまうと、`MATCH AGAINST`に`LIMIT`がかかってしまい、その結果に対してサブクエリでの絞込が行われ意図した結果が返ってきません。（絞り込んだ結果に対して`LIMIT`がかかるべきところが、`LIMIT`をかけた結果から絞り込まれてしまう）

fast_order_limitするべきではないように思いますので、fast_order_limit最適化を行うかどうかの判定が間違っているのではないかと思います。

```sql
drop database if exists mroonga_fast_order_limit_test;
create database mroonga_fast_order_limit_test;
use mroonga_fast_order_limit_test;

DROP TABLE IF EXISTS `channels`;
CREATE TABLE `channels` (
  `id` int(11) NOT NULL,
  `name` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=Mroonga;

DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `id` int(11) NOT NULL,
  `channel_id` int(11),
  `user_id` int(11),  
  PRIMARY KEY (`id`)
) ENGINE=Mroonga;

DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `channel_id` int(11),
  `text` varchar(512),
  PRIMARY KEY (`id`),
  FULLTEXT KEY `index_messages_on_text` (`text`)
) ENGINE=Mroonga;

INSERT INTO channels(id, name) VALUES (1, "foo");
INSERT INTO permissions(id, channel_id, user_id) VALUES (1, 1, 1);

INSERT INTO messages(id, channel_id, text) VALUES (1, 1, "test1");
INSERT INTO messages(id, channel_id, text) VALUES (2, 1, "test2");
INSERT INTO messages(id, channel_id, text) VALUES (3, 2, "test3");

# Search query includes subquery
# This query should return id:1, id:2, however, actually returned id:2
SELECT `messages`.*
FROM `messages`
WHERE `messages`.`channel_id` IN
    (SELECT `channels`.`id`
     FROM `channels`
     INNER JOIN `permissions` ON `channels`.`id` = `permissions`.`channel_id`
     WHERE `permissions`.`user_id` = 1)
  AND (match(text) against('*D+ test' IN boolean MODE))
  AND `messages`.`channel_id` = 1
ORDER BY `messages`.`id` DESC
LIMIT 2;
```

## Expected Behavior
```
+----+------------+-------+
| id | channel_id | text  |
+----+------------+-------+
|  2 |          1 | test2 |
|  1 |          1 | test1 |
+----+------------+-------+
```

## Current Behavior
```
+----+------------+-------+
| id | channel_id | text  |
+----+------------+-------+
|  2 |          1 | test2 |
+----+------------+-------+
```

## Environment
This issue can be reproduced on only MySQL 5.7

| MySQL | Mroonga | Groonga | Result | fast_order_limit |
|---|---|---|---|---|
| 5.6.35 | 6.13 | 6.1.5 | Valid | NOT APPLIED |
| 5.7.17 | 6.13 | 6.1.5 | Failed | OPTIMIZED |
| 5.6.38 | 7.09 | 7.0.9 | Valid | NOT APPLIED |
| 5.7.20 | 7.09 | 7.0.9 | Failed | OPTIMIZED |

**Comment by kou** [comment]
Thanks for your well written report.
It seems that Mroonga 7.10 works well for the case. Can you confirm it with Mroonga 7.10?

**Comment by ashphy** [comment]
It works fine on the Mroonga 7.10. condition_push_down seems to be perfect.

**Comment by kou** [comment]
No problem.
Can you confirm that Mroonga 7.10 really fixes this case in real world data?

**Comment by ashphy** [comment]
Yes, I've been updated my application, and tested.

**Comment by kou** [comment]
Thanks. That's good to hear.
