### ISSUE TITLE
[centos7] mariadb10.2-mroonga  yum install時にdependency error

### ISSUE THREAD

**Issue by sho-suzuki** [mroonga/mroonga#186]
お世話になっております。
centos7でmariadb10.2＋mroongaをyum installしようとした所、下記エラーがでました。

コマンド

```bash
yum update -y
yum install -y http://packages.groonga.org/centos/groonga-release-1.3.0-1.noarch.rpm
yum makecache
yum install -y mariadb-10.2-mroonga groonga-tokenizer-mecab groonga-normalizer-mysql groonga-devel
```

エラー内容

```bash
--> Finished Dependency Resolution
Error: Package: mariadb-10.2-mroonga-7.10-1.el7.centos.x86_64 (groonga)
           Requires: MariaDB-server = 10.2.11-1.el7.centos
           Available: MariaDB-server-10.2.12-1.el7.centos.x86_64 (mariadb)
               MariaDB-server = 10.2.12-1.el7.centos
Error: Package: mariadb-10.2-mroonga-7.10-1.el7.centos.x86_64 (groonga)
           Requires: MariaDB-client = 10.2.11-1.el7.centos
           Available: MariaDB-client-10.2.12-1.el7.centos.x86_64 (mariadb)
               MariaDB-client = 10.2.12-1.el7.centos
```

**Comment by s-yata** [comment]
Docker の CentOS 7 で試してみたところ，同じエラーになりました．
実行結果を添付しておきます．

[centos7-mroonga-install.log.txt](https://github.com/mroonga/mroonga/files/1624769/centos7-mroonga-install.log.txt)

http://mroonga.org/ja/docs/install/centos.html の手順を見ると `sudo systemctl start mariadb` が入っているので mariadb の開始が必要なのかとも思いましたが， Docker だと systemd が動いていないので試せませんでした．

**Comment by kou** [comment]
報告ありがとうございます。MariaDB 10.2の新しいバージョンがでたからですね。すぐに気付けるわけではないのでこういう報告はとても助かります。
パッケージを更新してみたので試してみてもらえますか？

**Comment by s-yata** [comment]
前回と同じく Docker で試してみたところ， http://mroonga.org/ja/docs/install/centos.html に書いてある手順でインストールできました（と思います）．
`Enter password` のところでエラーが出ていますが，通常の環境であれば大丈夫なはずです．

ログを添付しておきます．

[centos7-mroonga-install.with-mariadb-repo.log.txt](https://github.com/mroonga/mroonga/files/1629321/centos7-mroonga-install.with-mariadb-repo.log.txt)

一度テストでリポジトリの設定を忘れていたのですが，そのときは上で報告されているのと同様のエラーになりました．

[centos7-mroonga-install.without-mariadb-repo.log.txt](https://github.com/mroonga/mroonga/files/1629323/centos7-mroonga-install.without-mariadb-repo.log.txt)

**Comment by sho-suzuki** [comment]
@kou @s-yata 早速の対応ありがとうございました！
本日再度試したところ無事インストールできました。
