### ISSUE TITLE
[ubuntu][16.04.3 LTS (Xenial Xerus)][mariadb]install時にdependency error

### ISSUE THREAD

**Issue by sho-suzuki** [mroonga/mroonga#187]
お世話になっております。
http://mroonga.org/ja/docs/install/ubuntu.html
に従い、installを実行した所下記エラーがでました。

# command

```bash
sudo apt-get install -y -V software-properties-common lsb-release
sudo add-apt-repository -y universe
sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu $(lsb_release --short --codename)-security main restricted"

sudo add-apt-repository -y ppa:groonga/ppa
sudo apt-get update
sudo apt-get install -y -V mariadb-server-mroonga groonga-tokenizer-mecab
```

# error

```bash
# apt-get install -y -V mariadb-server-mroonga groonga-tokenizer-mecab
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています
状態情報を読み取っています... 完了
インストールすることができないパッケージがありました。おそらく、あり得
ない状況を要求したか、(不安定版ディストリビューションを使用しているの
であれば) 必要なパッケージがまだ作成されていなかったり Incoming から移
動されていないことが考えられます。
以下の情報がこの問題を解決するために役立つかもしれません:

以下のパッケージには満たせない依存関係があります:
 mariadb-server-mroonga : 依存: mariadb-server-10.0-mroonga (= 7.10-2~xenial1) しかし、インストールされようとしていません
                          依存: mariadb-server (= 10.0.31-0ubuntu0.16.04.2) しかし、インストールされようとしていません
E: 問題を解決することができません。壊れた変更禁止パッケージがあります。
```

**Comment by kou** [comment]
報告ありがとうございます。
https://packages.ubuntu.com/search?keywords=mariadb-server のxenial-updatesのmariadb-server-10.0パッケージのバージョンが10.0.33-0ubuntu0.16.04.1になったら更新します！

MariaDBのパッケージは1月16日更新されたみたいなので、近いうちにpackages.ubuntu.comの情報も最新になると思います。

**Comment by kou** [comment]
更新されていたのでパッケージをアップロードしました。再度試してみてください。

**Comment by sho-suzuki** [comment]
本日試したらインストールできました。対応有難うございました。

追加で質問なのですが、ubuntuでmariadb10.1, 10.2, 10.3系のmroongaバンドル版をインストールする手順はありますでしょうか？（上記だと10.0のみですよね）

**Comment by kenhys** [comment]
> 追加で質問なのですが、ubuntuでmariadb10.1, 10.2, 10.3系のmroongaバンドル版をインストールする手順はありますでしょうか？（上記だと10.0のみですよね）

https://downloads.mariadb.org/mariadb/repositories/#mirror=yamagata-university&distro=Ubuntu&distro_release=xenial--ubuntu_xenial&version=10.1
を利用してインストールするやりかたがあります。
ただし、10.1の場合はMroongaが既定では有効になっていないので、`INSTALL PLUGIN Mroonga SONAME 'ha_mroonga.so';`を実行して有効にする必要があります。
10.2以降の場合はmariadb-plugin-mroongaパッケージをインストールすれば使えるようになります。（ただしいずれも若干古いバージョンのMroongaとなります。)
