### ISSUE TITLE
Percona's gap lock detection prevents ALTER when AUTOCOMMIT=0

### ISSUE THREAD

**Issue by impimp** [mroonga/mroonga#188]
Percona Server supports gap lock detection: if a transactional storage engine does not support gap locks and a gap lock is being attempted while the transaction isolation level is either REPEATABLE READ or SERIALIZABLE, the following SQL error will be returned to the client and no actual gap lock will be taken on the affected rows.
(https://www.percona.com/doc/percona-server/LATEST/myrocks/gap_locks_detection.html#gap-locks-detection)

Above protection is triggered when an ALTER is executed on a Mroonga table in wrapper mode with 
`SET AUTOCOMMIT = 0`

**Steps to reproduce**
```
mysql> CREATE TABLE t (i int(11) NOT NULL, col1 varchar(256) DEFAULT NULL, PRIMARY KEY (i) ) ENGINE=Mroonga DEFAULT CHARSET=latin1 COMMENT='engine "InnoDB"';
Query OK, 0 rows affected (0.05 sec)

mysql> SET AUTOCOMMIT=0;
Query OK, 0 rows affected (0.00 sec)

mysql> ALTER TABLE t ENGINE=InnoDB;
ERROR 1105 (HY000): Using Gap Lock without full unique key in multi-table or multi-statement transactions is not allowed. You need to either rewrite queries to use all unique key columns in WHERE equal conditions, or rewrite to single-table, single-statement transaction.  Query: ALTER TABLE t ENGINE=InnoDB
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
