### ISSUE TITLE
Percona Server 5.6.39-83.1がリリースされたので対応お願いします。

### ISSUE THREAD

**Issue by iiiiyyyy** [mroonga/mroonga#194]
Percona Server 5.6の新しいバージョンがリリースされたので対応お願いします。
https://www.percona.com/doc/percona-server/5.6/release-notes/Percona-Server-5.6.39-83.1.html

**Comment by komainu8** [comment]
ご連絡ありがとうございます！
パッケージを更新しましたので、ご確認いただければと思います。

**Comment by iiiiyyyy** [comment]
ご対応ありがとうございました。
更新することができました。
