### ISSUE TITLE
Percona Server 5.6.40-84.0 と 5.7.22-22 がリリースされたので対応お願いします。

### ISSUE THREAD

**Issue by iiiiyyyy** [mroonga/mroonga#207]
Percona Server 5.6の新しいバージョンがリリースされたので対応お願いします。
https://www.percona.com/doc/percona-server/5.6/release-notes/Percona-Server-5.6.40-84.0.html

Percona Server 5.7の新しいバージョンがリリースされたので対応お願いします。
https://www.percona.com/doc/percona-server/5.7/release-notes/Percona-Server-5.7.22-22.html

5.6のみ使用していますが、5.7もリリースされていたので合わせて記載しました。

**Comment by komainu8** [comment]
ご連絡ありがとうございます！
対応まで少々おまちください。

**Comment by komainu8** [comment]
@iiiiyyyy パッケージを更新いたしましたので、ご確認いただければと思います。

**Comment by iiiiyyyy** [comment]
ご対応ありがとうございました。
5.6で更新できることを確認しました。

5.7で確認をしていませんが、Issueをクローズしても問題ないでしょうか。

**Comment by komainu8** [comment]
確認結果のご報告ありがとうございます。
私の方で、5.7 でインストール出来ることを確認しましたので、クローズいただいて問題ありません。

**Comment by iiiiyyyy** [comment]
了解しました。
確認完了ですのでクローズします。
