### ISSUE TITLE
Percona Server 5.6.41-84.1 がリリースされたので対応お願いします。

### ISSUE THREAD

**Issue by iiiiyyyy** [mroonga/mroonga#210]
Percona Server 5.6の新しいバージョンがリリースされたので対応お願いします。
https://www.percona.com/doc/percona-server/5.6/release-notes/Percona-Server-5.6.41-84.1.html

**Comment by komainu8** [comment]
@iiiiyyyy ご連絡ありがとうございます。

現在、Travis CIでテストが失敗しており、これらを修正して対応となりますので、
Percona Server 5.6.41-84.1 の対応は今月末リリース時となりそうです。

**Comment by kenhys** [comment]
@iiiiyyyy パッケージをアップロードしたので更新できると思います。

**Comment by iiiiyyyy** [comment]
更新することが出来ました。
ご対応ありがとうございました。
