### ISSUE TITLE
aptのパッケージ更新

### ISSUE THREAD

**Issue by Filriya** [mroonga/mroonga#216]
数日前からaptでmysql-server-mroongaをインストールできなくなりました。

環境 ubuntu16.04

$ sudo apt-get install -y -V mysql-server-mroonga
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
mysql-server-mroonga : Depends: mysql-server-5.7-mroonga (= 8.07-2~xenial1) but it is not going to be installed
Depends: mysql-server (= 5.7.23-0ubuntu0.16.04.1)
E: Unable to correct problems, you have held broken packages.

パッケージの更新よろしくお願いします。

**Comment by kenhys** [comment]
@Filriya パッケージを更新しておきました。
報告ありがとうございます！

**Comment by Filriya** [comment]
@kenhys ありがとうございます！助かります！
