### ISSUE TITLE
Travis CI: mysql-5.6 and mysql-5.7 are failed

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#229]
https://travis-ci.org/mroonga/mroonga/jobs/494710378#L881-L885

> WARNING: The following packages cannot be authenticated!
>  mysql-common libmysqlclient18 mysql-community-client mysql-client
>  mysql-community-server libmysqlclient-dev mysql-community-test mysql-server
>  mysql-testsuite
> E: There were unauthenticated packages and -y was used without --allow-unauthenticated

It seems that it's an apt related problem.

@komainu8 @kenhys Could you fix this?

**Comment by komainu8** [comment]
We have fixed this issue by below commit.
ee2f51fc8b01bc7d185678e70523bcc07a70c824
