### ISSUE TITLE
Add packages for MySQL 8

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#236]
MySQL 8 support isn't completed yet but providing packages are useful for test.

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/commit/a9cc99e761235765c55786512d5edcc57b81d74d でパッケージのビルドを走らせるのに必要なものをコミット。
[build.log](https://github.com/mroonga/mroonga/files/3226567/build.log)

ただし、rpmbuildはまだ調整しないといけない。

**Comment by kenhys** [comment]
mysql.specをrpmbuild -bcしたときには、次のようにmy_config.hは生成されていた。

```
[root@localhost mysql-8.0.16]# pwd
/root/rpmbuild/BUILD/mysql-8.0.16
[root@localhost mysql-8.0.16]# ll debug/include/
total 832
drwxr-xr-x. 2 root root     67 May 29 02:26 CMakeFiles
-rw-r--r--. 1 root root   2435 May 29 02:26 cmake_install.cmake
-rw-r--r--. 1 root root   9133 May 29 02:26 config.h
-rw-r--r--. 1 root root    314 May 29 02:26 CTestTestfile.cmake
-rw-r--r--. 1 root root   7411 May 29 02:26 Makefile
-rw-r--r--. 1 root root   9133 May 29 02:26 my_config.h
-rw-r--r--. 1 root root   7459 May 29 02:27 mysqlclient_ername.h
-rw-r--r--. 1 root root 582760 May 29 02:27 mysqld_ername.h
-rw-r--r--. 1 root root 210414 May 29 02:27 mysqld_error.h
-rw-r--r--. 1 root root   1158 May 29 02:26 mysql_version.h
```

**Comment by kou** [comment]
`my_config.h`って`mysql-community-devel`の中に入っていない？

**Comment by kou** [comment]
入っていないなら`--with-mysql-build`すればいいと思うけど、できればパッケージに含まれているやつの方がいいかな。

**Comment by kenhys** [comment]
はいってなかったです。

```
root@localhost mysql-8.0.16]# rpm -q mysql-community-devel
mysql-community-devel-8.0.16-2.el7.x86_64
[root@localhost mysql-8.0.16]# rpm -ql mysql-community-devel | grep my_config
```

**Comment by kenhys** [comment]
`--with-mysql-build` を試してみる。

**Comment by kenhys** [comment]
c++11が有効になっていなさそう。
[build.take6.log](https://github.com/mroonga/mroonga/files/3230711/build.take6.log)

**Comment by kenhys** [comment]
autoconf-archiveがインストールされていなかった。

**Comment by kenhys** [comment]
古いほうのコンパイラが使われていそう。

```
configure:19227: checking if g++ supports -std=gnu++14
configure:19249: g++ -c  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wall -Wextra -Wno-unused-parameter -Wno-strict-aliasing -Wno-deprecated -std=gnu++14 -Werror  conftest.cpp >&5
g++: error: unrecognized command line option '-std=gnu++14'
configure:19249: $? = 1
configure: failed program was:
```

**Comment by kenhys** [comment]
scl enable devtoolset-8しとかないといけなそう。

**Comment by kenhys** [comment]
↑ここまでのを入れ込んで通しでビルドしてみる。

**Comment by kenhys** [comment]
https://travis-ci.org/mroonga/mroonga/jobs/538125765
と同じエラーが出るところまでビルドが進んだ。

**Comment by kenhys** [comment]
#if の条件をミスっていた。なおしておこう。

**Comment by kenhys** [comment]
https://github.com/mroonga/mroonga/pull/240 でなおる (my_byteorder.hがincludeされ間接的にlittle_endian.hがincludeされるので) と思ったがそうでもなかった。

**Comment by kenhys** [comment]
あぁ、修正もれがあったことに気づいた。

**Comment by kenhys** [comment]
現状：
9.03のリリースのときには #241 がまだマージされていなかったのでビルドに失敗してパッケージのビルドまでたどりつけていなかった。
make buildでパッケージのビルドが走る仕組みは用意してあるので、次回はパッケージのビルドまですすめられるはず。

**Comment by kou** [comment]
これは閉じてもいいですか？

**Comment by kenhys** [comment]
はい、閉じてもよいやつなのでcloseします。
