### ISSUE TITLE
Reuse Groonga's packages/apt/update-repository.sh

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#251]
And use "The Groonga Project" for "Origin" in configuration file for `apt-ftparchive generate`.

**Comment by kenhys** [comment]
fixed via [packages apt: update Origin: "The Groonga Project"]( https://github.com/groonga/groonga/commit/de10a0bba7ac8e2696931428dd4b35dd3e5d9d67)

**Comment by kenhys** [comment]
changed to use [packages apt: use script in Groonga repository ](https://github.com/mroonga/mroonga/commit/007cb37ba36c6e059d7f63f5b8a1d4d9a9e840cf)

**Comment by kenhys** [comment]
Done!
