### ISSUE TITLE
近傍検索の不具合？

### ISSUE THREAD

**Issue by yamanaka-worth** [mroonga/mroonga#272]
＜テーブル＞
```sql
CREATE TABLE IF NOT EXISTS `tbl_hogehoge` (
  `record_id` mediumint(9) PRIMARY KEY AUTO_INCREMENT,
  `line_no` mediumint(9) DEFAULT NULL,
  `line_content` longtext,
) ENGINE=Mroonga DEFAULT CHARSET utf8mb4;

ALTER TABLE `tbl_hogehoge`
ADD FULLTEXT `line_content` (`line_content`) COMMENT 'tokenizer "TokenBigramSplitSymbolAlphaDigit"';
ALTER TABLE `tbl_hogehoge`
ADD FULLTEXT `line_content_u` (`line_content`) COMMENT 'tokenizer "TokenUnigram"';
```

＜insert＞
```sql
insert into tbl_hogehoge (line_no,line_content) values (4038,'夫熱病者．皆傷寒之類也．或愈或死．其死皆以六七日間．其愈皆以十日以上者何也．夫巨陽者．諸陽之属也．其脈連於風府．故為諸陽主気．人之傷於寒也．故則為病熱．熱雖甚不死．其両感於寒而病者必死．夫両傷於寒病者．一日則巨陽与**少陰**倶病．故頭痛口乾．煩満而渇（足太陽膀胱之経足**少陰**是腎心経也）二日足陽明与足太陰倶病．則腹満体熱．不食譫語（足陽明胃之経足太**陰脾**之経也）三日則足少陽与足厥陰倶病．則耳聾嚢縮．水漿不入口．則不知人．六日而死矣（足少陽胆之経足厥陰肝
之経也）是為六経陰陽表裏者也．陽為腑主表．陰為臓主裏．臓腑倶病．故曰両感．三日而死者．為一日両経受病．故雲両感．是表裏倶病．故六日而死矣．')
```

＜Select＞
```sql
SELECT record_id,line_no
FROM tbl_hogehoge USE INDEX (line_content)
WHERE MATCH(line_content) AGAINST('*SS line_content *N12 \"少陰 陰脾\"'IN BOOLEAN MODE)
```

＜期待する結果＞
```text
Empty set (0.00 sec)
```
※2つ目の「少陰」とその後ろの「陰脾」は、３７文字はなれているので該当しないはず
＜実際の結果＞
```text
| record_id | line_no |
+-----------+---------+
|    222328 |    4038 |
+-----------+---------+
1 row in set (0.01 sec) 
```

※`AGAINST('*SS line_content *N12`　以上とすると該当してしまう。
`AGAINST('*SS line_content *N11` とすると、`Empty`となる

何かわかりますでしょうか。
お手数をおかけします。

**Comment by komainu8** [comment]
ご連絡ありがとうございます。
確かに、おかしな動作になっている気がします。手元で再現させて確認してみます。

**Comment by yamanaka-worth** [comment]
komainu8様
ありがとうございます。
各ソフトのバージョンは次の通りです。
CentOS					
	CentOS Linux release 7.4.1708 (Core)							
Apache						
	Server version: Apache/2.4.6 (CentOS)							
	Server built:   Apr 24 2019 13:45:48							
Mariadb				
	mysql  Ver 15.1 Distrib 10.3.14-MariaDB, for Linux (x86_64) using readline 5.1													
mronnga								
　　MariaDB > SHOW VARIABLES LIKE 'mroonga_version';
 　　mroonga_version　 9.01
groonga							
　　MariaDB > SELECT mroonga_command('status');
	"version":"9.0.2",
	"n_queries":0,
	"cache_hit_rate":0.0,
	"command_version":1,
	"default_command_version":1,
	"max_command_version":3
以上です。
よろしくお願いいたします。

**Comment by komainu8** [comment]
バージョンの情報ありがとうございます。大変助かります。
原因が特定でき次第ご連絡させていただきます。

**Comment by yamanaka-worth** [comment]
ありがとうございます。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by komainu8** [comment]
根本的な原因は、まだ調査中なのですが、`TokenUnigram`を使っていると発生することがわかりました。

**Comment by yamanaka-worth** [comment]
ありがとうございます。
１文字での検索を行う必要があり、TokenUnigramの全文インデックスを作りました。
こちらでも回避策がないか試してみます。
引続き、何卒よろしくお願いいたします。

**Comment by komainu8** [comment]
原因はまだデバッグ中なのですが、`TokenBigramSplitSymbolAlphaDigit`でも、１文字での検索は可能です。
以下の例が適切かはわかりませんが、以下のように１文字の検索キーワードでも、期待するレコードがヒットします。

```sql
CREATE TABLE IF NOT EXISTS tbl_hogehoge (
  record_id mediumint(9) PRIMARY KEY AUTO_INCREMENT,
  line_no mediumint(9) DEFAULT NULL,
  line_content longtext ) ENGINE = Mroonga DEFAULT CHARSET utf8;

insert into tbl_hogehoge (line_no,line_content) values (1,'其愈皆以十日以上者何也');
insert into tbl_hogehoge (line_no,line_content) values (2,'夫巨陽者');
insert into tbl_hogehoge (line_no,line_content) values (3,'諸陽之属也');

ADD FULLTEXT line_content (line_content) 
  COMMENT 'tokenizer "TokenBigramSplitSymbolAlphaDigit"';

SELECT record_id,line_no 
  FROM tbl_hogehoge 
  USE INDEX (line_content)
  WHERE MATCH(line_content) AGAINST('+夫' IN BOOLEAN MODE);
+-----------+---------+
| record_id | line_no |
+-----------+---------+
|         2 |       2 |
+-----------+---------+
1 row in set (0.03 sec)

SELECT record_id,line_no 
  FROM tbl_hogehoge 
  USE INDEX (line_content)
  WHERE MATCH(line_content) AGAINST('+也' IN BOOLEAN MODE);
+-----------+---------+
| record_id | line_no |
+-----------+---------+
|         1 |       1 |
|         3 |       3 |
+-----------+---------+
2 rows in set (0.00 sec)
```

したがって、ひとまず`TokenUnigram`のインデックスを作成しないという方法で回避するのは、いかがでしょうか？

`TokenUnigram`のインデックスを作成しない場合は、近傍検索も期待どおり動作しました。

```sql
SELECT record_id,line_no
  FROM tbl_hogehoge USE INDEX (line_content)
  WHERE MATCH(line_content) AGAINST('*SS line_content *N12 "少陰 陰脾"'IN BOOLEAN MODE);
Empty set (0.06 sec)

SELECT record_id,line_no
  FROM tbl_hogehoge
  USE INDEX (line_content)
  WHERE MATCH(line_content) AGAINST('*SS line_content *N37 "少陰 陰脾"'IN BOOLEAN MODE);
+-----------+---------+
| record_id | line_no |
+-----------+---------+
|         1 |    4038 |
+-----------+---------+
1 row in set (0.00 sec)

SELECT record_id,line_no
  FROM tbl_hogehoge
  USE INDEX (line_content)
  WHERE MATCH(line_content) AGAINST('*SS line_content *N36 "少陰 陰脾"'IN BOOLEAN MODE);
Empty set (0.00 sec)
```

**Comment by yamanaka-worth** [comment]
ありがとうございます。
こちらでもTokenUnigram無しで確認いたします。
結果はご連絡いたします。

**Comment by kou** [comment]
この挙動で期待通りです。

`*N`はクエリーをトークナイズして、その各トークンの間に指定した個数のトークンがあってもマッチさせる検索です。

`TokenUnigram`は`少陰 陰脾`を次の4つのトークンにトークナイズします。

  * `少`
  * `陰`
  * `陰`
  * `脾`

そのため、`少...{12文字以内}...陰...{12文字以内}...陰...{12文字以内}...脾`というテキストにマッチします。

文字単位でなく単語？（私は中国語がわからないので「少陰」が単語と呼ぶべきものかわからないのですが。。。）単位で近傍検索したい場合は、単語単位でトークナイズするトークナイザーを指定する必要があります。`TokenBigram`系は2文字の単語ではそれっぽく動くでしょうが、それはたまたま対象が2文字で単語だからです。3文字の単語とかでは単語単位で近傍検索しません。

中国語用のトークナイザーとして https://github.com/kenhys/groonga-tokenizer-friso があります。
