### ISSUE TITLE
特定のデータでINSERT処理が終わらない

### ISSUE THREAD

**Issue by fugafigs** [mroonga/mroonga#300]
Mroongaにて特定のデータのINSERTを行った場合に、
INSERTが終わらない現象が発生します。

show processlist -> killだけでは復旧できないため、
kill QueryID後、mysqldをkill -9して復旧しています。

### 再現手順

```
--  1. 下記のテーブルを作成
CREATE TABLE `page_cache` (
  `url` varchar(512) DEFAULT NULL,
  `title` text,
  `description` text,
  `keywords` text,
  `firstview` text,
  `body` mediumtext,
  FULLTEXT KEY `title` (`title`) COMMENT 'tokenizer "TokenMecab" normalizer "NormalizerAuto"',
  FULLTEXT KEY `description` (`description`) COMMENT 'tokenizer "TokenMecab" normalizer "NormalizerAuto"',
  FULLTEXT KEY `keywords` (`keywords`) COMMENT 'tokenizer "TokenMecab" normalizer "NormalizerAuto"',
  FULLTEXT KEY `body` (`body`) COMMENT 'tokenizer "TokenMecab" normalizer "NormalizerAuto"'
) ENGINE=Mroonga DEFAULT CHARSET=utf8mb4

-- 2. 添付ファイルのINSERT文を実行
\. dump.txt 
```
[dump.txt](https://github.com/mroonga/mroonga/files/4089671/dump.txt)

### 現象再現時のgroonga.log

```
2020-01-21 07:09:33.005167|w|9741|14045700: [token_next] ignore an empty token: <TokenMecab>: <     >
```
↑上記のログが延々と流れ続ける。

**Comment by fugafigs** [comment]
### 再現環境

* OS
     * Amazon Linux AMI release 2018.03
* 導入パケージ(2.5.5. CentOS 6（Percona Server 5.7パッケージを利用)を元にインストール)
    * percona-release-1.0-7.noarch, percona-server-57-mroonga-9.11-1.el6.x86_64
    * groonga-tokenizer-mecab-9.1.1-1.el6.x86_64

### その他

* normalizerは、指定してもしなくても現象が発生

**Comment by komainu8** [comment]
すみません。
いただいたクエリーなのですが、文字化けしているように見えまして、ファイルの文字コードはUTF-8のようなのですが、こちらでエディタの文字コードを合わせても文字化けしたままになっています。

これは、文字化けしたまま、INSERTしていますか？
それとも、 @fugafigs さんの環境では、文字化けしていないクエリーをINSERTしていますか？

**Comment by fugafigs** [comment]
クロール時に漢字コードの変換にミスしたらしく、文字化けしたままINSERTされていると思います。@komainu8

**Comment by komainu8** [comment]
なるほど。わかりました。ありがとうございます！
手元で再現するか試してみます。

**Comment by fugafigs** [comment]
再現可能でしょうか？
私の環境で文字化けしていないデータでも、再現するデータを見つけたのでこちらも共有しておきます。
[dump2.txt](https://github.com/mroonga/mroonga/files/4090291/dump2.txt)

**Comment by komainu8** [comment]
ありがとうございます！たすかります。

**Comment by fugafigs** [comment]
page_cacheテーブルにINSERTする際、
フィールドをtrimしてからINSERTを行ったところINSERTが無事終わりました。
空白のみのデータの場合に現象が起こっていたようでした。

あと、記載し忘れていましたがMecabの辞書はneologdを使っています。
```
filename:       /usr/lib64/mecab/dic/mecab-ipadic-neologd/sys.dic
version:        102
charset:        UTF8
type:   0
size:   5918451
left size:      1316
right size:     1316
```

**Comment by komainu8** [comment]
情報ありがとうございます！

頂いたデータを流してみたのですが、手元では再現しませんでした。
空白のみのデータを作って、再現をためしてみます。

**Comment by fugafigs** [comment]
@komainu8 
色々試していたところ、下記でも現象が発生してしまいました。
```
select mroonga_command('tokenize TokenMecab "  "');
```
さすがに、これは私の環境側に問題がありそうなので、
もう一度ベースのAMIから環境を作り直して再現の有無を確認しようと思います。

メインの仕事の合間にやるため、少し時間がかかるかもしれませんが、結果が分かり次第こちらにコメントします。

**Comment by komainu8** [comment]
貴重な情報をありがとうございます！

こちらでも、もう少しみてみます。

**Comment by kou** [comment]
`echo "  " | mecab -Owakati | cat --show-all`はどうなりますか？

**Comment by fugafigs** [comment]
下記のようになります。
```bash
echo " " | mecab -Owakati | cat --show-all
$
```

**Comment by kou** [comment]
うーん、`echo "  "`（スペース2つ）だとどうなりますか？

**Comment by fugafigs** [comment]
2つ以上でも同じ結果になりました。

**Comment by kou** [comment]
`select mroonga_command('tokenize TokenMecab " "');`はスペース1つでも再現しますか？2つ以上必要ですか？

**Comment by fugafigs** [comment]
1つでも再現します。

**Comment by kou** [comment]
↓でも再現しますよね？

```bash
rm -rf /tmp/db && mkdir -p /tmp/db && groonga -n /tmp/db/db tokenize TokenMecab '" "'
```

**Comment by fugafigs** [comment]
```bash
rm -rf /tmp/db && mkdir -p /tmp/db && groonga -n /tmp/db/db tokenize TokenMecab '" "'
[[0,1579766817.225198,0.0003757476806640625],[]]
```
↑こんな感じになります。

**Comment by kou** [comment]
あら、再現しないんですか。
それは妙ですね。

`select mroonga_command('tokenize TokenMecab "  "');`で再現するならGroongaレベルでの話なはずなんですけどねぇ。

次の結果はどうなりますか？

```bash
rm -rf /tmp/db && mkdir -p /tmp/db && groonga -n /tmp/db/db status
```

```sql
select mroonga_command('status');
```

**Comment by fugafigs** [comment]
```
rm -rf /tmp/db && mkdir -p /tmp/db && groonga -n /tmp/db/db status
[[0,1579767094.570135,8.344650268554688e-05],{"alloc_count":347,"starttime":1579767094,"start_time":1579767094,"uptime":0,"version":"9.1.1","n_queries":0,"cache_hit_rate":0.0,"command_version":1,"default_command_version":1,"max_command_version":3,"n_jobs":0}]
```

```
mysql> select mroonga_command('status');
{"alloc_count":991,"starttime":1579686333,"start_time":1579686333,"uptime":80823,"version":"9.1.1","n_queries":0,"cache_hit_rate":0.0,"command_version":1,"default_command_version":1,"max_command_version":3,"n_jobs":0}
```

**Comment by fugafigs** [comment]
クリーンインストールしたところ、現象は出なくなりました。
とりあえず、状況の報告まで。

```
mysql> select mroonga_command('tokenize TokenMecab " 　"');
+-----------------------------------------------+
| mroonga_command('tokenize TokenMecab " 　"')  |
+-----------------------------------------------+
| []                                            |
+-----------------------------------------------+
1 row in set (0.00 sec)
```
@komainu8 @kou
貴重なお時間取らせてしまいまして、申し訳ありません.

**Comment by kou** [comment]
なんだったんでしょうね。
現象がなくなったということなので閉じますね。
