### ISSUE TITLE
Mroongaをインストールする際に依存性処理エラーが発生します。

### ISSUE THREAD

**Issue by asyahana** [mroonga/mroonga#321]
Mroongaをインストールする際に、下記のように依存性処理エラーが発生し、インストールできません。先月末にMroongaが10.02にアップデートされましたが、その影響でしょうか？（4月半ばにした時には特に問題なかったのですが、その時はMroonga 10.01でした）

お手数ですが回避策等がございましたら、ご教授お願い致します。

【環境】
OS：CentOS 7.7.1908（Core）
DB：MariaDB Ver.10.4-stable

[root@gitsv-centos ~]# systemctl start mariadb
[root@gitsv-centos ~]# yum install -y --enablerepo=epel mariadb-10.4-mroonga 
読み込んだプラグイン:fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.net
 * epel: ftp.iij.ad.jp
 * extras: mirrors.cat.net
 * updates: mirrors.cat.net
依存性の解決をしています
--> トランザクションの確認を実行しています。
---> パッケージ mariadb-10.4-mroonga.x86_64 0:10.02-1.el7 を インストール
--> 依存性の処理をしています: MariaDB-client = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: MariaDB-server = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: groonga-libs >= 8.0.4 のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: groonga-normalizer-mysql のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: libgroonga.so.0()(64bit) のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> トランザクションの確認を実行しています。
---> パッケージ groonga-libs.x86_64 0:10.0.2-1.el7 を インストール
--> 依存性の処理をしています: msgpack のパッケージ: groonga-libs-10.0.2-1.el7.x86_64
--> 依存性の処理をしています: libzstd のパッケージ: groonga-libs-10.0.2-1.el7.x86_64
--> 依存性の処理をしています: libzstd.so.1()(64bit) のパッケージ: groonga-libs-10.0.2-1.el7.x86_64
--> 依存性の処理をしています: libmsgpackc.so.2()(64bit) のパッケージ: groonga-libs-10.0.2-1.el7.x86_64
---> パッケージ groonga-normalizer-mysql.x86_64 0:1.1.4-1.el7 を インストール
---> パッケージ mariadb-10.4-mroonga.x86_64 0:10.02-1.el7 を インストール
--> 依存性の処理をしています: MariaDB-client = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: MariaDB-server = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> トランザクションの確認を実行しています。
---> パッケージ libzstd.x86_64 0:1.4.4-1.el7 を インストール
---> パッケージ mariadb-10.4-mroonga.x86_64 0:10.02-1.el7 を インストール
--> 依存性の処理をしています: MariaDB-client = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
--> 依存性の処理をしています: MariaDB-server = 10.4.12-1.el7.centos のパッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64
---> パッケージ msgpack.x86_64 0:3.1.0-4.el7 を インストール
--> 依存性解決を終了しました。
エラー: パッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64 (groonga-centos)
             要求: MariaDB-client = 10.4.12-1.el7.centos
            インストール: MariaDB-client-10.4.13-1.el7.centos.x86_64 (@mariadb)
                MariaDB-client = 10.4.13-1.el7.centos
            利用可能: MariaDB-client-10.4.11-1.el7.centos.x86_64 (mariadb)
                MariaDB-client = 10.4.11-1.el7.centos
            利用可能: MariaDB-client-10.4.12-1.el7.centos.x86_64 (mariadb)
                MariaDB-client = 10.4.12-1.el7.centos
エラー: パッケージ: mariadb-10.4-mroonga-10.02-1.el7.x86_64 (groonga-centos)
             要求: MariaDB-server = 10.4.12-1.el7.centos
            インストール: MariaDB-server-10.4.13-1.el7.centos.x86_64 (@mariadb)
                MariaDB-server = 10.4.13-1.el7.centos
            利用可能: MariaDB-server-10.4.11-1.el7.centos.x86_64 (mariadb)
                MariaDB-server = 10.4.11-1.el7.centos
            利用可能: MariaDB-server-10.4.12-1.el7.centos.x86_64 (mariadb)
                MariaDB-server = 10.4.12-1.el7.centos
 問題を回避するために --skip-broken を用いることができます。
 これらを試行できます: rpm -Va --nofiles --nodigest
[root@gitsv-centos ~]# 
[MroongaInstallErrorTerminal.txt](https://github.com/mroonga/mroonga/files/4626215/MroongaInstallErrorTerminal.txt)

**Comment by komainu8** [comment]
ご連絡ありがとうございます！
これは、Mroongaパッケージを更新する必要がありまして、現在対応しているところでので、少々おまちいただければと思います。

対応が完了しましたらこちらにもその旨、連絡させていただきます。

**Comment by asyahana** [comment]
迅速なお返事ありがとうございます！
パッケージ更新という事で承知致しました。

どうぞよろしくお願い致します。

**Comment by kou** [comment]
更新したので試してみてもらえますか？

**Comment by asyahana** [comment]
迅速な対応ありがとうございます！
試してみたところ、無事インストールできました。

当IssueはCloseさせていただきます。
ありがとうございました。
