### ISSUE TITLE
Percona-Server-client-57.x86_64 0:5.7.30-33.1.el7へUpdateが出来ません。

### ISSUE THREAD

**Issue by Yuutakasan** [mroonga/mroonga#338]
Percona serverがバージョンアップしたようです。対応お願いします。

# yum update
読み込んだプラグイン:fastestmirror, priorities
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                                                                                           | 5.2 kB  00:00:00
Including mirror: ftp-srv2.kddilabs.jp
Including mirror: ftp.riken.jp
Including mirror: ftp.iij.ad.jp
Including mirror: ftp.jaist.ac.jp
Including mirror: ftp.nara.wide.ad.jp
Including mirror: ftp.tsukuba.wide.ad.jp
Including mirror: ftp.yz.yamagata-u.ac.jp
 * base: ftp-srv2.kddilabs.jp
Including mirror: ftp.ne.jp
Including mirror: ftp.yz.yamagata-u.ac.jp
 * elrepo: ftp.ne.jp
Including mirror: ftp.iij.ad.jp
Including mirror: ftp.jaist.ac.jp
 * epel: ftp.iij.ad.jp
Including mirror: ftp-srv2.kddilabs.jp
Including mirror: ftp.riken.jp
Including mirror: ftp.iij.ad.jp
Including mirror: ftp.jaist.ac.jp
Including mirror: ftp.nara.wide.ad.jp
Including mirror: ftp.tsukuba.wide.ad.jp
Including mirror: ftp.yz.yamagata-u.ac.jp
 * extras: ftp-srv2.kddilabs.jp
Including mirror: ftp-srv2.kddilabs.jp
Including mirror: ftp.riken.jp
Including mirror: ftp.iij.ad.jp
Including mirror: ftp.jaist.ac.jp
Including mirror: ftp.nara.wide.ad.jp
Including mirror: ftp.tsukuba.wide.ad.jp
Including mirror: ftp.yz.yamagata-u.ac.jp
 * updates: ftp-srv2.kddilabs.jp
base                                                                                                                           | 3.6 kB  00:00:00
cuda                                                                                                                           | 3.0 kB  00:00:00
draios                                                                                                                         | 2.9 kB  00:00:00
elrepo                                                                                                                         | 2.9 kB  00:00:00
epel                                                                                                                           | 4.7 kB  00:00:00
extras                                                                                                                         | 2.9 kB  00:00:00
groonga-centos                                                                                                                 | 2.9 kB  00:00:00
mysql-connectors-community                                                                                                     | 2.5 kB  00:00:00
mysql-tools-community                                                                                                          | 2.5 kB  00:00:00
mysql57-community                                                                                                              | 2.5 kB  00:00:00
newrelic-infra/x86_64/signature                                                                                                |  836 B  00:00:00
newrelic-infra/x86_64/signature                                                                                                | 2.5 kB  00:00:00 !!!
percona-release-noarch                                                                                                         | 2.9 kB  00:00:00
percona-release-x86_64                                                                                                         | 2.9 kB  00:00:00
treasuredata                                                                                                                   | 2.9 kB  00:00:00
updates                                                                                                                        | 2.9 kB  00:00:00
(1/12): cuda/primary_db                                                                                                        | 622 kB  00:00:00
(2/12): epel/x86_64/group_gz                                                                                                   |  95 kB  00:00:00
(3/12): epel/x86_64/updateinfo                                                                                                 | 1.0 MB  00:00:00
(4/12): elrepo/primary_db                                                                                                      | 412 kB  00:00:00
(5/12): extras/7/x86_64/primary_db                                                                                             | 206 kB  00:00:00
(6/12): epel/x86_64/primary_db                                                                                                 | 6.9 MB  00:00:00
(7/12): groonga-centos/7/x86_64/primary_db                                                                                     | 2.4 MB  00:00:00
(8/12): newrelic-infra/x86_64/primary_db                                                                                       | 109 kB  00:00:00
(9/12): draios/x86_64/primary_db                                                                                               |  21 kB  00:00:00
(10/12): updates/7/x86_64/primary_db                                                                                           | 4.5 MB  00:00:00
(11/12): percona-release-noarch/7/primary_db                                                                                   |  24 kB  00:00:00
(12/12): percona-release-x86_64/7/primary_db                                                                                   | 1.1 MB  00:00:01
依存性の解決をしています
--> トランザクションの確認を実行しています。
---> パッケージ Percona-Server-client-57.x86_64 0:5.7.30-33.1.el7 を 更新
--> 依存性の処理をしています: Percona-Server-client-57 = 5.7.30-33.1.el7 のパッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64
---> パッケージ Percona-Server-client-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ Percona-Server-rocksdb-57.x86_64 0:5.7.30-33.1.el7 を 更新
---> パッケージ Percona-Server-rocksdb-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ Percona-Server-server-57.x86_64 0:5.7.30-33.1.el7 を 更新
--> 依存性の処理をしています: Percona-Server-server-57 = 5.7.30-33.1.el7 のパッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64
---> パッケージ Percona-Server-server-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ Percona-Server-shared-57.x86_64 0:5.7.30-33.1.el7 を 更新
---> パッケージ Percona-Server-shared-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ Percona-Server-shared-compat-57.x86_64 0:5.7.30-33.1.el7 を 更新
---> パッケージ Percona-Server-shared-compat-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ Percona-Server-tokudb-57.x86_64 0:5.7.30-33.1.el7 を 更新
---> パッケージ Percona-Server-tokudb-57.x86_64 0:5.7.31-34.1.el7 を アップデート
---> パッケージ curl.x86_64 0:7.29.0-57.el7 を 更新
---> パッケージ curl.x86_64 0:7.29.0-57.el7_8.1 を アップデート
---> パッケージ ibacm.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ ibacm.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ iwpmd.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ iwpmd.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ kernel.x86_64 0:3.10.0-1127.19.1.el7 を インストール
---> パッケージ kernel-debug-devel.x86_64 0:3.10.0-1127.18.2.el7 を 更新
---> パッケージ kernel-debug-devel.x86_64 0:3.10.0-1127.19.1.el7 を アップデート
---> パッケージ kernel-devel.x86_64 0:3.10.0-1127.19.1.el7 を インストール
---> パッケージ kernel-headers.x86_64 0:3.10.0-1127.18.2.el7 を 更新
---> パッケージ kernel-headers.x86_64 0:3.10.0-1127.19.1.el7 を アップデート
---> パッケージ kernel-tools.x86_64 0:3.10.0-1127.18.2.el7 を 更新
---> パッケージ kernel-tools.x86_64 0:3.10.0-1127.19.1.el7 を アップデート
---> パッケージ kernel-tools-libs.x86_64 0:3.10.0-1127.18.2.el7 を 更新
---> パッケージ kernel-tools-libs.x86_64 0:3.10.0-1127.19.1.el7 を アップデート
---> パッケージ libcurl.x86_64 0:7.29.0-57.el7 を 更新
---> パッケージ libcurl.x86_64 0:7.29.0-57.el7_8.1 を アップデート
---> パッケージ libibumad.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ libibumad.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ libibverbs.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ libibverbs.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ libibverbs-utils.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ libibverbs-utils.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ librdmacm.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ librdmacm.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ librdmacm-utils.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ librdmacm-utils.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ newrelic-infra.x86_64 0:1.12.1-1.el7 を 更新
---> パッケージ newrelic-infra.x86_64 0:1.12.3-1.el7 を アップデート
---> パッケージ nfs-utils.x86_64 1:1.3.0-0.66.el7 を 更新
---> パッケージ nfs-utils.x86_64 1:1.3.0-0.66.el7_8 を アップデート
---> パッケージ nri-redis.x86_64 0:1.4.0-1 を 更新
---> パッケージ nri-redis.x86_64 0:1.5.1-1 を アップデート
---> パッケージ opensm-libs.x86_64 0:3.3.21-2.el7 を 更新
---> パッケージ opensm-libs.x86_64 0:3.3.21-3.el7_8 を アップデート
---> パッケージ percona-release.noarch 0:1.0-22 を 更新
---> パッケージ percona-release.noarch 0:1.0-24 を アップデート
---> パッケージ percona-toolkit.x86_64 0:3.2.0-1.el7 を 更新
---> パッケージ percona-toolkit.x86_64 0:3.2.1-1.el7 を アップデート
---> パッケージ python-perf.x86_64 0:3.10.0-1127.18.2.el7 を 更新
---> パッケージ python-perf.x86_64 0:3.10.0-1127.19.1.el7 を アップデート
---> パッケージ rdma-core.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ rdma-core.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ srp_daemon.x86_64 0:22.4-2.el7_8 を 更新
---> パッケージ srp_daemon.x86_64 0:22.4-4.el7_8 を アップデート
---> パッケージ sysdig.x86_64 0:0.26.7-1 を 更新
---> パッケージ sysdig.x86_64 0:0.27.0-1 を アップデート
---> パッケージ systemd.x86_64 0:219-73.el7_8.8 を 更新
---> パッケージ systemd.x86_64 0:219-73.el7_8.9 を アップデート
---> パッケージ systemd-libs.x86_64 0:219-73.el7_8.8 を 更新
---> パッケージ systemd-libs.x86_64 0:219-73.el7_8.9 を アップデート
---> パッケージ systemd-sysv.x86_64 0:219-73.el7_8.8 を 更新
---> パッケージ systemd-sysv.x86_64 0:219-73.el7_8.9 を アップデート
--> 依存性解決を終了しました。
--> トランザクションの確認を実行しています。
---> パッケージ Percona-Server-client-57.x86_64 0:5.7.30-33.1.el7 を 更新
--> 依存性の処理をしています: Percona-Server-client-57 = 5.7.30-33.1.el7 のパッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64
---> パッケージ Percona-Server-server-57.x86_64 0:5.7.30-33.1.el7 を 更新
--> 依存性の処理をしています: Percona-Server-server-57 = 5.7.30-33.1.el7 のパッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64
---> パッケージ kernel.x86_64 0:3.10.0-1062.9.1.el7 を 削除
---> パッケージ kernel-devel.x86_64 0:3.10.0-1062.9.1.el7 を 削除
--> 依存性解決を終了しました。
エラー: パッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64 (@groonga-centos)
             要求: Percona-Server-client-57 = 5.7.30-33.1.el7
            削除中: Percona-Server-client-57-5.7.30-33.1.el7.x86_64 (@percona-release-x86_64)
                Percona-Server-client-57 = 5.7.30-33.1.el7
            次のものにより更新された: : Percona-Server-client-57-5.7.31-34.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.31-34.1.el7
            利用可能: Percona-Server-client-57-5.7.10-1rc1.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-1rc1.1.el7
            利用可能: Percona-Server-client-57-5.7.10-2rc2.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-2rc2.1.el7
            利用可能: Percona-Server-client-57-5.7.10-3.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-3.1.el7
            利用可能: Percona-Server-client-57-5.7.11-4.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.11-4.1.el7
            利用可能: Percona-Server-client-57-5.7.12-5.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.12-5.1.el7
            利用可能: Percona-Server-client-57-5.7.13-6.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.13-6.1.el7
            利用可能: Percona-Server-client-57-5.7.14-7.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.14-7.1.el7
            利用可能: Percona-Server-client-57-5.7.14-8.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.14-8.1.el7
            利用可能: Percona-Server-client-57-5.7.15-9.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.15-9.1.el7
            利用可能: Percona-Server-client-57-5.7.16-10.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.16-10.1.el7
            利用可能: Percona-Server-client-57-5.7.17-11.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-11.1.el7
            利用可能: Percona-Server-client-57-5.7.17-12.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-12.1.el7
            利用可能: Percona-Server-client-57-5.7.17-13.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-13.1.el7
            利用可能: Percona-Server-client-57-5.7.18-14.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-14.1.el7
            利用可能: Percona-Server-client-57-5.7.18-15.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-15.1.el7
            利用可能: Percona-Server-client-57-5.7.18-16.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-16.1.el7
            利用可能: Percona-Server-client-57-5.7.19-17.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.19-17.1.el7
            利用可能: Percona-Server-client-57-5.7.20-18.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-18.1.el7
            利用可能: Percona-Server-client-57-5.7.20-19.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-19.1.el7
            利用可能: Percona-Server-client-57-5.7.21-20.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-20.1.el7
            利用可能: Percona-Server-client-57-5.7.21-21.2.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.2.el7
            利用可能: Percona-Server-client-57-5.7.21-21.3.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.3.el7
            利用可能: Percona-Server-client-57-5.7.22-22.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.22-22.1.el7
            利用可能: Percona-Server-client-57-5.7.23-23.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-23.1.el7
            利用可能: Percona-Server-client-57-5.7.23-24.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-24.1.el7
            利用可能: Percona-Server-client-57-5.7.23-25.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-25.1.el7
            利用可能: Percona-Server-client-57-5.7.24-26.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-26.1.el7
            利用可能: Percona-Server-client-57-5.7.24-27.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-27.1.el7
            利用可能: Percona-Server-client-57-5.7.25-28.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.25-28.1.el7
            利用可能: Percona-Server-client-57-5.7.26-29.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.26-29.1.el7
            利用可能: Percona-Server-client-57-5.7.27-30.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.27-30.1.el7
            利用可能: Percona-Server-client-57-5.7.28-31.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.28-31.1.el7
            利用可能: Percona-Server-client-57-5.7.29-32.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.29-32.1.el7
エラー: パッケージ: percona-server-57-mroonga-10.05-1.el7.x86_64 (@groonga-centos)
             要求: Percona-Server-server-57 = 5.7.30-33.1.el7
            削除中: Percona-Server-server-57-5.7.30-33.1.el7.x86_64 (@percona-release-x86_64)
                Percona-Server-server-57 = 5.7.30-33.1.el7
            次のものにより更新された: : Percona-Server-server-57-5.7.31-34.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.31-34.1.el7
            利用可能: Percona-Server-server-57-5.7.10-1rc1.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-1rc1.1.el7
            利用可能: Percona-Server-server-57-5.7.10-2rc2.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-2rc2.1.el7
            利用可能: Percona-Server-server-57-5.7.10-3.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-3.1.el7
            利用可能: Percona-Server-server-57-5.7.11-4.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.11-4.1.el7
            利用可能: Percona-Server-server-57-5.7.12-5.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.12-5.1.el7
            利用可能: Percona-Server-server-57-5.7.13-6.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.13-6.1.el7
            利用可能: Percona-Server-server-57-5.7.14-7.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.14-7.1.el7
            利用可能: Percona-Server-server-57-5.7.14-8.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.14-8.1.el7
            利用可能: Percona-Server-server-57-5.7.15-9.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.15-9.1.el7
            利用可能: Percona-Server-server-57-5.7.16-10.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.16-10.1.el7
            利用可能: Percona-Server-server-57-5.7.17-11.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-11.1.el7
            利用可能: Percona-Server-server-57-5.7.17-12.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-12.1.el7
            利用可能: Percona-Server-server-57-5.7.17-13.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-13.1.el7
            利用可能: Percona-Server-server-57-5.7.18-14.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-14.1.el7
            利用可能: Percona-Server-server-57-5.7.18-15.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-15.1.el7
            利用可能: Percona-Server-server-57-5.7.18-16.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-16.1.el7
            利用可能: Percona-Server-server-57-5.7.19-17.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.19-17.1.el7
            利用可能: Percona-Server-server-57-5.7.20-18.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-18.1.el7
            利用可能: Percona-Server-server-57-5.7.20-19.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-19.1.el7
            利用可能: Percona-Server-server-57-5.7.21-20.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-20.1.el7
            利用可能: Percona-Server-server-57-5.7.21-21.2.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.2.el7
            利用可能: Percona-Server-server-57-5.7.21-21.3.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.3.el7
            利用可能: Percona-Server-server-57-5.7.22-22.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.22-22.1.el7
            利用可能: Percona-Server-server-57-5.7.23-23.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-23.1.el7
            利用可能: Percona-Server-server-57-5.7.23-24.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-24.1.el7
            利用可能: Percona-Server-server-57-5.7.23-25.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-25.1.el7
            利用可能: Percona-Server-server-57-5.7.24-26.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-26.1.el7
            利用可能: Percona-Server-server-57-5.7.24-27.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-27.1.el7
            利用可能: Percona-Server-server-57-5.7.25-28.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.25-28.1.el7
            利用可能: Percona-Server-server-57-5.7.26-29.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.26-29.1.el7
            利用可能: Percona-Server-server-57-5.7.27-30.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.27-30.1.el7
            利用可能: Percona-Server-server-57-5.7.28-31.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.28-31.1.el7
            利用可能: Percona-Server-server-57-5.7.29-32.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.29-32.1.el7
 問題を回避するために --skip-broken を用いることができます。
 これらを試行できます: rpm -Va --nofiles --nodigest

**Comment by komainu8** [comment]
ご連絡ありがとうございます！

https://github.com/mroonga/mroonga/commit/62bb9bf99ee989d37f86b9b5f9c40423cea18a81 にて対応済みなので、今月末のリリースのときにパッケージを更新します。

**Comment by Yuutakasan** [comment]
@komainu8 回答ありがとうございます！
