### ISSUE TITLE
依存性エラーについて

### ISSUE THREAD

**Issue by naoki7090624** [mroonga/mroonga#339]
Mroongaをインストールする際に以下の依存エラーが発生しました。

```
# sudo yum install -y mysql57-community-mroonga
読み込んだプラグイン:fastestmirror
Loading mirror speeds from cached hostfile
 * base: d36uatko69830t.cloudfront.net
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
依存性の解決をしています
--> トランザクションの確認を実行しています。
---> パッケージ mysql57-community-mroonga.x86_64 0:10.05-1.el7 を インストール
--> 依存性の処理をしています: mysql-community-client = 5.7.31-1.el7 のパッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64
--> 依存性の処理をしています: mysql-community-server = 5.7.31-1.el7 のパッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64
--> 依存性解決を終了しました。
エラー: パッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64 (groonga-centos)
             要求: mysql-community-server = 5.7.31-1.el7
エラー: パッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64 (groonga-centos)
             要求: mysql-community-client = 5.7.31-1.el7
 問題を回避するために --skip-broken を用いることができます。
 これらを試行できます: rpm -Va --nofiles --nodigest
```

現在、MySQL 5.7.29を使用しています。
MySQL 5.7.31ではなく、MySQL 5.7.29の環境でmroongaをインストールしたいのですが、可能でしょうか？

**Comment by komainu8** [comment]
Mroongaのパッケージは、特定のバージョンのMySQLと一緒にビルドする必要があり、今提供しているパッケージはMySQL 5.7.31でビルドされています。
したがって、今提供しているパッケージを使うにはMySQL 5.7.31が必要なため、MySQL 5.7.29の環境にはインストールできません。

MySQL 5.7.29 の環境でMroongaを動かすには、 Mroongaをソースからインストールする必要があります。
その際、MySQL 5.7.29 もソースからインストールする必要があるので注意してください。

ソースからインストールする際は、以下のドキュメントを参照いただければと思います。
https://mroonga.org/ja/docs/install/others.html#dependencies

**Comment by naoki7090624** [comment]
迅速なご回答ありがとうございます！
ソースインストールの方法で試してみたいと思います。

解決いたしましたので、本IssueはCloseさせていただきます。

**Comment by naoki7090624** [comment]
迅速なご回答ありがとうございます！

自分の環境では、MySQL5.7系がソースによってインストールされています。
先ほど、MySQL 5.7.31に変更してから```# sudo yum install -y mysql57-community-mroonga```をしたのですが、同様にエラーが発生しました。
```
読み込んだプラグイン:fastestmirror
Loading mirror speeds from cached hostfile
 * base: d36uatko69830t.cloudfront.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
依存性の解決をしています
--> トランザクションの確認を実行しています。
---> パッケージ mysql57-community-mroonga.x86_64 0:10.05-1.el7 を インストール
--> 依存性の処理をしています: mysql-community-client = 5.7.31-1.el7 のパッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64
--> 依存性の処理をしています: mysql-community-server = 5.7.31-1.el7 のパッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64
--> 依存性解決を終了しました。
エラー: パッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64 (groonga-centos)
             要求: mysql-community-server = 5.7.31-1.el7
エラー: パッケージ: mysql57-community-mroonga-10.05-1.el7.x86_64 (groonga-centos)
             要求: mysql-community-client = 5.7.31-1.el7
 問題を回避するために --skip-broken を用いることができます。
 これらを試行できます: rpm -Va --nofiles --nodigest
```

MySQLをソースからインストールしている場合は、Mroongaもソースからインストールする必要がありますか？

**Comment by komainu8** [comment]
いえ、MySQLがソースからインストールされていても、`mysql57-community-mroonga`をパッケージでインストールした場合は、MySQLのパッケージ(`mysql-community-server-5.7.31-1.el7.x86_64`と`mysql-community-client-5.7.31-1.el7.x86_64`) をインストールするので、上記のエラーは発生しないはずです。

既に、MySQLのパッケージを`yum`でインストールしていないでしょうか？

**Comment by naoki7090624** [comment]
ご返事ありがとうございます。
yum listで確認したところ、MySQLに関係ありそうなパッケージは以下のものがありました。
```
akonadi-mysql.x86_64                        1.9.2-4.el7                base     
apr-util-mysql.x86_64                       1.5.2-6.el7                base     
dovecot-mysql.x86_64                        1:2.2.36-6.el7             base     
freeradius-mysql.x86_64                     3.0.13-10.el7_6            base     
libdbi-dbd-mysql.x86_64                     0.8.3-16.el7               base     
mysql-connector-java.noarch                 1:5.1.25-3.el7             base     
mysql-connector-odbc.x86_64                 5.2.5-8.el7                base     
pcp-pmda-mysql.x86_64                       4.3.2-7.el7_8              updates  
php-mysql.x86_64                            5.4.16-48.el7              base     
php-mysqlnd.x86_64                          5.4.16-48.el7              base     
qt-mysql.i686                               1:4.8.7-8.el7              base     
qt-mysql.x86_64                             1:4.8.7-8.el7              base     
qt5-qtbase-mysql.i686                       5.9.7-2.el7                base     
qt5-qtbase-mysql.x86_64                     5.9.7-2.el7                base     
redland-mysql.x86_64                        1.0.16-6.el7               base     
rsyslog-mysql.x86_64                        8.24.0-52.el7_8.2          updates 
```

既に最新のMySQLがソースからインストールされていた場合、以下のコマンドの実行は不要かなと思いましたが、必要でしょうか？
```
% sudo yum install -y http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
% sudo yum install -y yum-utils
% sudo yum-config-manager --disable mysql56-community
% sudo yum-config-manager --enable mysql57-community
```

**Comment by komainu8** [comment]
すみません。自分の回答を見直してみましたが、ちゃんと質問に回答できていませんね。。。

まず、
> MySQLをソースからインストールしている場合は、Mroongaもソースからインストールする必要がありますか？
という質問についてですが、これは、「ソースからインストールしたMySQLを使いたい場合」は必要です。

MySQLをソースからインストールしている状態で、Mroongaのパッケージ(`mysql57-community-mroonga`)をインストールすると、MySQLのパッケージ(`mysql-community-server`と`mysql-community-client`)がインストールされ、`yum`でインストールされたMroongaのパッケージ(`mysql57-community-mroonga`)は、MySQLのパッケージ(`mysql-community-server`と`mysql-community-client`)を使います。 (ソースからインストールしたMySQLは使いません。)

なので、ソースからインストールしたMySQL上でMroongaを使いたい場合は、Mroongaもソースからインストールする必要があります。

---

> 既に最新のMySQLがソースからインストールされていた場合、以下のコマンドの実行は不要かなと思いましたが、必要でしょうか？

なるほど。ありがとうございます。
依存性エラーは、これらのコマンドを実行していないのが原因です。

```
% sudo yum install -y http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
% sudo yum install -y yum-utils
% sudo yum-config-manager --disable mysql56-community
% sudo yum-config-manager --enable mysql57-community
```

CentOS7 は、デフォルトでMySQLのリポジトリーが登録されていないので、上記のコマンドを実行して、MySQLのリポジトリを登録する必要があります。
上記を実行していないと、Mroongaをインストールする際にMySQLを探しに行きますが、MySQLのリポジトリーが登録されていないため、MySQLのパッケージが見つからず、依存性エラーとなります。

```
% sudo yum install -y http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
```

上記のコマンドを実行して、MySQLのリポジトリーを登録後、下記のコマンドを実行してMySQL5.7のリポジトリーに切り替えます。
(MySQLは5.6, 5.7, 8.0のリポジトリーがあり、デフォルトはMySQL5.6のリポジトリーが参照されるため、下記のコマンドを実行してMySQL5.7のリポジトリーに切り替える必要があります。)

```
% sudo yum-config-manager --disable mysql56-community
% sudo yum-config-manager --enable mysql57-community
```

---

したがって、以下のコマンドを実行すれば、依存性エラーは解決すると思います。
(少なくとも、私の手元で再現させた環境では解決しました。)

```
% sudo yum install -y http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
% sudo yum install -y yum-utils
% sudo yum-config-manager --disable mysql56-community
% sudo yum-config-manager --enable mysql57-community
```

ただ、前述の通り、上記のコマンドを実行した後に `sudo yum install -y mysql57-community-mroonga`  を実行すると、パッケージのMySQLが使用され、ソースからインストールしたMySQLは使用されないので、ソースからインストールしたMySQL上でMroongaを使いたい場合は、Mroongaもソースからインストールする必要があります。

**Comment by naoki7090624** [comment]
凄くご丁寧なご回答ありがとうございます。

依存性エラーはMySQLのリポジトリーを登録していなかったことが原因だったのですね。
ソースからインストールしたMySQLを使いたいので、パッケージではなく、ソースからインストールしてみようと思います。

解決いたしましたので、本チケットはクローズさせていただきます。
迅速で丁寧なご解説ありがとうございました。本当に助かりました。

**Comment by kou** [comment]
まとめ：

  * MySQLをソースからインストールしている場合はMroongaもソースからインストールしなければいけない。
  * Mroongaをソースからインストールする場合はmysql57-community-mroongaなどのMroongaのパッケージは必要ない。
  * Groongaもソースからインストールする場合はpackages.groonga.orgをYumに登録する必要もない。
  * Groongaはパッケージを使う場合はpackages.groonga.orgをYumに登録する必要はあるが、Mroongaのパッケージをインストールする必要はない。（前述の通り）
