### ISSUE TITLE
Percona server 8系の対応について

### ISSUE THREAD

**Issue by Yuutakasan** [mroonga/mroonga#340]
CentOS8系＋Percona Server8系の対応はされないのでしょうか？

**Comment by komainu8** [comment]
https://github.com/mroonga/mroonga/commit/5fce6cd545550451cf26d44ed314d27123cdb56e にて対応しました。
パッケージがまだアップロードできてないので、もう少々おまちいただけますか？

**Comment by Yuutakasan** [comment]
待っておりました！ありがとうございました！

**Comment by komainu8** [comment]
Mroonga 10.06にて対応したためCloseします。

**Comment by Yuutakasan** [comment]
ありがとうございました！
