### ISSUE TITLE
Debian packaging installed repo naming scheme: bullseye: /updates -> -security

### ISSUE THREAD

**Issue by ottok** [mroonga/mroonga#353]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970068

Still applies at least for https://github.com/mroonga/mroonga/blob/master/tools/travis/install.sh

> With the release of Debian bullseye and later, security updates are
> provided in the bullseye-security suite instead of bullseye/updates.
> 
> In the mariadb source package there appears to be a script that
> generates a Debian chroot/container for building packages and that
> script relies on appears to write an apt sources.list that will
> not provide security updates for packages installed in the
> chroot/container. I suggest that this script check the version of the
> Debian release in question using distro-info and then if the release is
> 11 or higher, then use $release-security otherwise use $release/updates
> as before. It is much better to use distro-info than to hard-code the
> release version numbers. It might even be a good idea to include the
> security suite information in distro-info itself and look it up there.
> 
> I filed this bug at severity minor since the script in question doesn't
> appear to be used for any part of the Debian packages nor for building
> the Debian packages, but only for some upstream packages.
> 
>    $ grep -A6 -B10 /updates  storage/mroonga/packages/apt/build-deb.sh
>    distribution=$(lsb_release --id --short | tr 'A-Z' 'a-z')
>    case "${distribution}" in
>      debian)
>        component=main
>        run cat <<EOF > /etc/apt/sources.list.d/groonga.list
>    deb http://packages.groonga.org/debian/ ${code_name} main
>    deb-src http://packages.groonga.org/debian/ ${code_name} main
>    EOF
>        if ! grep --quiet security /etc/apt/sources.list; then
>          run cat <<EOF > /etc/apt/sources.list.d/security.list
>    deb http://security.debian.org/ ${code_name}/updates main
>    deb-src http://security.debian.org/ ${code_name}/updates main
>    EOF
>        fi
>        run apt-get update
>        run apt-get install -y --allow-unauthenticated groonga-keyring
>        run apt-get update
>        ;;

**Comment by kou** [comment]
Thanks for forwarding this.

`storage/mroonga/packages/apt/build-deb.sh` can be removed by updating bundled Mroonga in MariaDB to the latest release. The latest Mroonga release doesn't include the file.

https://github.com/mroonga/mroonga/blob/master/tools/travis/install.sh#L38-L41registeres an APT source. But it registers an APT source for MariaDB. So it's unrelated to bullseye-security.

**Comment by pabs3** [comment]
@ottok sounds like this should be closed and forwarded to MariaDB instead, for removing the embedded copy of Mroonga (or maybe updating it). Is there any reason for MariaDB to embed Mroonga instead of depending on it?

**Comment by ottok** [comment]
This is nor a MariaDB issue, but clearly an issue with a piece of code in the Mroonga repository. Anyway, you fixed the issue by removing the code in https://github.com/mroonga/mroonga/commit/8aa9aa44a87a61861109aa99231de267719341cf, thus closing this issue now as resolved.
