### ISSUE TITLE
Percona-Server updateが出来ません。

### ISSUE THREAD

**Issue by Yuutakasan** [mroonga/mroonga#371]
$sudo yum update
読み込んだプラグイン:dkms-build-requires, getpagespeed, priorities, update-motd, upgrade-helper
amzn-main                                                                                                                      | 2.1 kB  00:00:00
amzn-updates                                                                                                                   | 3.8 kB  00:00:00
draios                                                                                                                         | 2.9 kB  00:00:00
groonga-centos                                                                                                                 | 3.0 kB  00:00:00
newrelic                                                                                                                       | 2.5 kB  00:00:00
newrelic-infra/x86_64/signature                                                                                                |  836 B  00:00:00
newrelic-infra/x86_64/signature                                                                                                | 2.5 kB  00:00:00 !!!
nginx                                                                                                                          | 2.9 kB  00:00:00
percona-release-noarch                                                                                                         | 2.9 kB  00:00:00
percona-release-x86_64                                                                                                         | 2.9 kB  00:00:00
prel-release-noarch                                                                                                            | 2.9 kB  00:00:00
wazuh_repo                                                                                                                     | 3.4 kB  00:00:00
77 packages excluded due to repository priority protections
依存性の解決をしています
--> トランザクションの確認を実行しています。
---> パッケージ Percona-Server-client-57.x86_64 0:5.7.31-34.1.el6 を 更新
--> 依存性の処理をしています: Percona-Server-client-57 = 5.7.31-34.1.el6 のパッケージ: percona-server-57-mroonga-10.07-1.el6.x86_64
---> パッケージ Percona-Server-client-57.x86_64 0:5.7.32-35.1.el6 を アップデート
---> パッケージ Percona-Server-server-57.x86_64 0:5.7.31-34.1.el6 を 更新
--> 依存性の処理をしています: Percona-Server-server-57 = 5.7.31-34.1.el6 のパッケージ: percona-server-57-mroonga-10.07-1.el6.x86_64
---> パッケージ Percona-Server-server-57.x86_64 0:5.7.32-35.1.el6 を アップデート
---> パッケージ Percona-Server-shared-57.x86_64 0:5.7.31-34.1.el6 を 更新
---> パッケージ Percona-Server-shared-57.x86_64 0:5.7.32-35.1.el6 を アップデート
---> パッケージ groonga-libs.x86_64 0:10.0.7-1.el6 を 更新
---> パッケージ groonga-libs.x86_64 0:10.0.9-1.el6 を アップデート
--> 依存性の処理をしています: libxxhash.so.0()(64bit) のパッケージ: groonga-libs-10.0.9-1.el6.x86_64
---> パッケージ groonga-tokenizer-mecab.x86_64 0:10.0.7-1.el6 を 更新
---> パッケージ groonga-tokenizer-mecab.x86_64 0:10.0.9-1.el6 を アップデート
--> 依存性解決を終了しました。
エラー: パッケージ: percona-server-57-mroonga-10.07-1.el6.x86_64 (@groonga-centos)
             要求: Percona-Server-server-57 = 5.7.31-34.1.el6
            削除中: Percona-Server-server-57-5.7.31-34.1.el6.x86_64 (installed)
                Percona-Server-server-57 = 5.7.31-34.1.el6
            次のものにより更新された: : Percona-Server-server-57-5.7.32-35.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.32-35.1.el6
            利用可能: Percona-Server-server-57-5.7.20-18.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-18.1.el6
            利用可能: Percona-Server-server-57-5.7.20-19.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-19.1.el6
            利用可能: Percona-Server-server-57-5.7.21-20.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-20.1.el6
            利用可能: Percona-Server-server-57-5.7.21-21.2.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.2.el6
            利用可能: Percona-Server-server-57-5.7.21-21.3.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.3.el6
            利用可能: Percona-Server-server-57-5.7.22-22.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.22-22.1.el6
            利用可能: Percona-Server-server-57-5.7.23-23.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-23.1.el6
            利用可能: Percona-Server-server-57-5.7.23-24.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-24.1.el6
            利用可能: Percona-Server-server-57-5.7.23-25.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-25.1.el6
            利用可能: Percona-Server-server-57-5.7.24-26.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-26.1.el6
            利用可能: Percona-Server-server-57-5.7.24-27.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-27.1.el6
            利用可能: Percona-Server-server-57-5.7.25-28.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.25-28.1.el6
            利用可能: Percona-Server-server-57-5.7.26-29.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.26-29.1.el6
            利用可能: Percona-Server-server-57-5.7.27-30.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.27-30.1.el6
            利用可能: Percona-Server-server-57-5.7.28-31.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.28-31.1.el6
            利用可能: Percona-Server-server-57-5.7.29-32.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.29-32.1.el6
            利用可能: Percona-Server-server-57-5.7.30-33.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.30-33.1.el6
エラー: パッケージ: percona-server-57-mroonga-10.07-1.el6.x86_64 (@groonga-centos)
             要求: Percona-Server-client-57 = 5.7.31-34.1.el6
            削除中: Percona-Server-client-57-5.7.31-34.1.el6.x86_64 (installed)
                Percona-Server-client-57 = 5.7.31-34.1.el6
            次のものにより更新された: : Percona-Server-client-57-5.7.32-35.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.32-35.1.el6
            利用可能: Percona-Server-client-57-5.7.20-18.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-18.1.el6
            利用可能: Percona-Server-client-57-5.7.20-19.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-19.1.el6
            利用可能: Percona-Server-client-57-5.7.21-20.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-20.1.el6
            利用可能: Percona-Server-client-57-5.7.21-21.2.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.2.el6
            利用可能: Percona-Server-client-57-5.7.21-21.3.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.3.el6
            利用可能: Percona-Server-client-57-5.7.22-22.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.22-22.1.el6
            利用可能: Percona-Server-client-57-5.7.23-23.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-23.1.el6
            利用可能: Percona-Server-client-57-5.7.23-24.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-24.1.el6
            利用可能: Percona-Server-client-57-5.7.23-25.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-25.1.el6
            利用可能: Percona-Server-client-57-5.7.24-26.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-26.1.el6
            利用可能: Percona-Server-client-57-5.7.24-27.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-27.1.el6
            利用可能: Percona-Server-client-57-5.7.25-28.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.25-28.1.el6
            利用可能: Percona-Server-client-57-5.7.26-29.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.26-29.1.el6
            利用可能: Percona-Server-client-57-5.7.27-30.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.27-30.1.el6
            利用可能: Percona-Server-client-57-5.7.28-31.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.28-31.1.el6
            利用可能: Percona-Server-client-57-5.7.29-32.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.29-32.1.el6
            利用可能: Percona-Server-client-57-5.7.30-33.1.el6.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.30-33.1.el6
エラー: パッケージ: groonga-libs-10.0.9-1.el6.x86_64 (groonga-centos)
             要求: libxxhash.so.0()(64bit)
 問題を回避するために --skip-broken を用いることができます。
 これらを試行できます: rpm -Va --nofiles --nodigest

**Comment by komainu8** [comment]
これを解決するには、パッケージの更新が必要なのですが、CentOS6は先日EOLを迎えたため、CentOS6 のyumリポジトリーのミラーが軒並み閉じられていて、現在、通常の方法ではCentOS6向けにMroongaのパッケージを作成できません。

そのため、MroongaもCentOS6のサポートをやめました。

CentOS7 以降で動かしていただければと思います。
