### ISSUE TITLE
Mroonga 11.00、MySQL 8.0: 外部キー制約が登録されない

### ISSUE THREAD

**Issue by ochaochaocha3** [mroonga/mroonga#393]
MySQL 8.0、Mroonga 11.00ストレージモードで `ENGINE=Mroonga` のテーブルを作成する場合、外部キー制約を設定してもMySQL側に登録されないようです。そのため、例えばRailsのマイグレーションで `foreign_key_exists?` の結果が実際のスキーマと矛盾した状態になります。

# 再現するSQL

## InnoDB用

```sql
DROP DATABASE IF EXISTS innodb_fk_test;

CREATE DATABASE innodb_fk_test;
USE innodb_fk_test;

CREATE TABLE referred (
  id int PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE refer (
  id int PRIMARY KEY AUTO_INCREMENT,
  id_referred int NOT NULL,
  CONSTRAINT id_referred FOREIGN KEY (id_referred) REFERENCES referred (id)
) ENGINE=InnoDB;

-- (1) SHOW CREATE TABLE refer
SHOW CREATE TABLE refer;

-- (2) information_schema.REFERENTIAL_CONSTRAINTS
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = "innodb_fk_test";

-- (3) information_schema.KEY_COLUMN_USAGE
SELECT * FROM information_schema.KEY_COLUMN_USAGE
  WHERE CONSTRAINT_SCHEMA = "innodb_fk_test";

-- (4) 外部キー制約を満たす値の挿入
INSERT INTO referred VALUES (1);
INSERT INTO refer VALUES (1, 1);
SELECT * FROM refer;

-- (5) 外部キー制約を満たさない値の挿入
INSERT INTO refer VALUES (2, 2);
```

## Mroonga用

```sql
DROP TABLE IF EXISTS mroonga_fk_test.refer;

DROP DATABASE IF EXISTS mroonga_fk_test;

CREATE DATABASE mroonga_fk_test;
USE mroonga_fk_test;

CREATE TABLE referred (
  id int PRIMARY KEY AUTO_INCREMENT
) ENGINE=Mroonga;

CREATE TABLE refer (
  id int PRIMARY KEY AUTO_INCREMENT,
  id_referred int NOT NULL,
  CONSTRAINT id_referred FOREIGN KEY (id_referred) REFERENCES referred (id)
) ENGINE=Mroonga;

-- (1) SHOW CREATE TABLE refer
SHOW CREATE TABLE refer;

-- (2) information_schema.REFERENTIAL_CONSTRAINTS
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = "mroonga_fk_test";

-- (3) information_schema.KEY_COLUMN_USAGE
SELECT * FROM information_schema.KEY_COLUMN_USAGE
  WHERE CONSTRAINT_SCHEMA = "mroonga_fk_test";

-- (4) 外部キー制約を満たす値の挿入
INSERT INTO referred VALUES (1);
INSERT INTO refer VALUES (1, 1);
SELECT * FROM refer;

-- (5) 外部キー制約を満たさない値の挿入
INSERT INTO refer VALUES (2, 2);
```

# 期待される結果

* `SHOW CREATE TABLE refer` に `CONSTRAINT id_referred FOREIGN KEY` が含まれる。
* `information_schema.REFERENTIAL_CONSTRAINTS` に `id_referred` の情報が含まれる。
* `information_schema.KEY_COLUMN_USAGE` に `id_referred` の情報が含まれる。
* 外部キー制約を満たさないデータを挿入できない。

# 結果

## MySQL 5.7.33の場合

Dockerイメージ「groonga/mroonga:mysql5733_mroonga1100」で実行しました。`ENGINE=InnoDB` の場合も `ENGINE=Mroonga` の場合も、期待どおりの結果になりました。

### `ENGINE=InnoDB` の場合

```
# (1) SHOW CREATE TABLE refer
Table	Create Table
refer	CREATE TABLE `refer` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `id_referred` int(11) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `id_referred` (`id_referred`),\n  CONSTRAINT `id_referred` FOREIGN KEY (`id_referred`) REFERENCES `referred` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

# (2) information_schema.REFERENTIAL_CONSTRAINTS
CONSTRAINT_NAME	TABLE_NAME	REFERENCED_TABLE_NAME
id_referred	refer	referred

# (3) information_schema.KEY_COLUMN_USAGE
CONSTRAINT_NAME	TABLE_NAME	COLUMN_NAME
PRIMARY	refer	id
id_referred	refer	id_referred
PRIMARY	referred	id

# (4) 外部キー制約を満たす値の挿入
id	id_referred
1	1

# (5) 外部キー制約を満たさない値の挿入
ERROR 1452 (23000) at line 31: Cannot add or update a child row: a foreign key constraint fails (`innodb_fk_test`.`refer`, CONSTRAINT `id_referred` FOREIGN KEY (`id_referred`) REFERENCES `referred` (`id`))
```

### `ENGINE=Mroonga` の場合

```
# (1) SHOW CREATE TABLE refer
Table	Create Table
refer	CREATE TABLE `refer` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `id_referred` int(11) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `id_referred` (`id_referred`),\n  CONSTRAINT `id_referred` FOREIGN KEY (`id_referred`) REFERENCES `mroonga_fk_test`.`referred` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT\n) ENGINE=Mroonga DEFAULT CHARSET=utf8mb4

# (2) information_schema.REFERENTIAL_CONSTRAINTS
CONSTRAINT_NAME	TABLE_NAME	REFERENCED_TABLE_NAME
id_referred	refer	referred

# (3) information_schema.KEY_COLUMN_USAGE
CONSTRAINT_NAME	TABLE_NAME	COLUMN_NAME
PRIMARY	refer	id
id_referred	refer	id_referred
PRIMARY	referred	id

# (4) 外部キー制約を満たす値の挿入
id	id_referred
1	1

# (5) 外部キー制約を満たさない値の挿入
ERROR 1452 (23000) at line 33: Cannot add or update a child row: a foreign key constraint fails (foreign record doesn't exist: <id_referred>:<2>)
```

## MySQL 8.0.23の場合

Dockerイメージ「groonga/mroonga:mysql8023_mroonga1100」で実行しました。

`ENGINE=InnoDB` の場合は期待どおりの結果でした。

`ENGINE=Mroonga` の場合は、Groongaにはインデックスカラムが設定されるものの、MySQLには外部キー制約が登録されていないようでした。そのため、外部キー制約を満たさない値の登録はできませんが、以下のようにMySQL側で予想外の結果となりました。

* `SHOW CREATE TABLE refer` に `CONSTRAINT id_referred FOREIGN KEY` が含まれない。
* `information_schema.REFERENTIAL_CONSTRAINTS` に `id_referred` の情報が含まれない。
* `information_schema.KEY_COLUMN_USAGE` に `id_referred` の情報が含まれない。

### `ENGINE=InnoDB` の場合

```
# (1) SHOW CREATE TABLE refer
Table	Create Table
refer	CREATE TABLE `refer` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `id_referred` int NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `id_referred` (`id_referred`),\n  CONSTRAINT `id_referred` FOREIGN KEY (`id_referred`) REFERENCES `referred` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

# (2) information_schema.REFERENTIAL_CONSTRAINTS
CONSTRAINT_NAME	TABLE_NAME	REFERENCED_TABLE_NAME
id_referred	refer	referred

# (3) information_schema.KEY_COLUMN_USAGE
CONSTRAINT_NAME	TABLE_NAME	COLUMN_NAME
PRIMARY	refer	id
id_referred	refer	id_referred
PRIMARY	referred	id

# (4) 外部キー制約を満たす値の挿入
id	id_referred
1	1

# (5) 外部キー制約を満たさない値の挿入
ERROR 1452 (23000) at line 31: Cannot add or update a child row: a foreign key constraint fails (`innodb_fk_test`.`refer`, CONSTRAINT `id_referred` FOREIGN KEY (`id_referred`) REFERENCES `referred` (`id`))
```

### `ENGINE=Mroonga` の場合

```
# (1) SHOW CREATE TABLE refer
Table	Create Table
refer	CREATE TABLE `refer` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `id_referred` int NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `id_referred` (`id_referred`)\n) ENGINE=Mroonga DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

# (2) information_schema.REFERENTIAL_CONSTRAINTS
（空集合のため表示されない）

# (3) information_schema.KEY_COLUMN_USAGE
CONSTRAINT_NAME	TABLE_NAME	COLUMN_NAME
PRIMARY	refer	id
PRIMARY	referred	id

# (4) 外部キー制約を満たす値の挿入
id	id_referred
1	1

# (5) 外部キー制約を満たさない値の挿入
ERROR 1452 (23000) at line 33: Cannot add or update a child row: a foreign key constraint fails (foreign record doesn't exist: <id_referred>:<2>)
```

**Comment by komainu8** [comment]
ご報告ありがとうございます。
調査内容を記載していきます。

---

`CONSTRAINT id_referred FOREIGN KEY`の出力は、`ha_mroonga::storage_get_foreign_key_create_info()`で実行している。
デバッガーでこの関数にブレイクポイントを貼ってみたが、ブレイクポイントにヒットしなかったので、Callされていない。

`ha_mroonga::storage_get_foreign_key_create_info()`は`ha_mroonga::get_foreign_key_create_info()`からCallされていて、`ha_mroonga::storage_get_foreign_key_create_info()`は、 https://github.com/mroonga/mroonga/commit/94a2831504073ef488788a655ab24e6a9ebd9513 のコミットで、`MRN_HANDLER_HAVE_FOREIGN_KEY_INFO`が定義されているときのみ有効になる。

`MRN_HANDLER_HAVE_FOREIGN_KEY_INFO`は、 https://github.com/mroonga/mroonga/commit/94a2831504073ef488788a655ab24e6a9ebd9513#diff-5dcc37b3699b0f6dd14d152d954665186cd73dbac2143c8fd5046858ee569c76R479-R481 のコードの通り、 MySQL 8.0.19より前のバージョンでのみ有効になるので、最新のMySQL 8.0.23では有効になっていない。

したがって、MySQL 8.0.23との組み合わせだと、Mroongaには、`CONSTRAINT id_referred FOREIGN KEY`を表示する処理がない。

なぜこうなっているのか？
MySQL 8.0.19から以下の変更が入っていてMroongaのハンドラーを呼ばずに、MySQLのレイヤーで処理するようになっている。

https://github.com/mysql/mysql-server/commit/b40a588c6b746788810253238e3702cc0f0a77ce#diff-cd5ac2db946c26a2668c92b5804888e2e68724aaee6b1a86c255e2271ef3f835L1389-R1484

そのため、MySQL 8.0.19以降では、 https://github.com/mroonga/mroonga/commit/94a2831504073ef488788a655ab24e6a9ebd9513 のコミットでMroongaから外部キー制約関係の情報を出力する関数を削除している。

`CONSTRAINT id_referred FOREIGN KEY` は、 https://github.com/mysql/mysql-server/commit/b40a588c6b746788810253238e3702cc0f0a77ce#diff-cd5ac2db946c26a2668c92b5804888e2e68724aaee6b1a86c255e2271ef3f835R1087 のあたりで出力されそうだが、そうなってないので、このあたりのコードに原因がありそう。

**Comment by ochaochaocha3** [comment]
調べていただきありがとうございます。MySQL 8.0.19以降で外部キー制約の表示処理が変わっていたとは存じませんでした。なかなか複雑な問題ですね…

補足として、アプリケーション（Ruby on Rails製）側で起こった問題（cre-ne-jp/log-archiver#254）について追記します。

#389 で報告いたしましたとおり、Mroonga 10.11以降では `ENGINE=Mroonga` かつ外部キー制約で参照されているテーブルの変更（カラム削除）でエラーが発生するようになりました。#389 が解決するまで、回避策として、一旦外部キー制約を削除してから被参照テーブルのスキーマ変更を行い、再度外部キー制約を設定し直すという方法を採ることにしました。MySQL 5.7の場合は、この回避策が成功しました。しかしMySQL 8.0.23の場合は、Railsのライブラリ（ActiveRecord）から「指定された外部キー制約が見つからない」と報告され、外部キー制約の削除に失敗するため、上記の回避策が失敗しました。

したがって、アプリケーション側で問題がない状態になるには、次の2点が満たされる必要があると考えました。

1. `ENGINE=InnoDB` の場合と同様に、`ENGINE=Mroonga` の場合も外部キー制約が発見される。
2. `ALTER TABLE DROP FOREIGN KEY` により、MySQL側、Groonga側ともに指定された外部キー制約が削除される。

1番にはRailsのActiveRecordの実装も影響するので、これについて調べてみました。Rails v6.1.3では、ActiveRecordのMySQLアダプタは、以下のSQL文を用いて外部キー制約の一覧を取得していました。

https://github.com/rails/rails/blob/v6.1.3/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L395-L410

```ruby
        fk_info = exec_query(<<~SQL, "SCHEMA")
          SELECT fk.referenced_table_name AS 'to_table',
                 fk.referenced_column_name AS 'primary_key',
                 fk.column_name AS 'column',
                 fk.constraint_name AS 'name',
                 rc.update_rule AS 'on_update',
                 rc.delete_rule AS 'on_delete'
          FROM information_schema.referential_constraints rc
          JOIN information_schema.key_column_usage fk
          USING (constraint_schema, constraint_name)
          WHERE fk.referenced_column_name IS NOT NULL
            AND fk.table_schema = #{scope[:schema]}
            AND fk.table_name = #{scope[:name]}
            AND rc.constraint_schema = #{scope[:schema]}
            AND rc.table_name = #{scope[:name]}
        SQL
```

このSQL文から、外部キー制約に関する情報は `information_schema` データベースの `referential_constraints` テーブルおよび `key_column_usage` テーブルから取得されることが分かりました。MySQL 8.0.23、Mroonga 11.00ストレージモードを使用した場合、本issueの説明文に記載いたしましたとおり、この2テーブルに外部キー制約情報が登録されないため、外部キー制約が一切設定されていないと誤認されたと考えられました。以上から、`SHOW CREATE TABLE` の表示だけでなく、上記2テーブルに外部キー制約情報が登録されるようにもなることが望ましいです。

2番については、外部キー制約のシンボル値が表示されず不明なため、試せていません。1番の解決後に確認できるようになると思われます。

**Comment by komainu8** [comment]
なるほど！補足と追加の情報ありがとうございます！助かります。

`information_schema`に登録されていない問題も確認する予定です。ただ、いきなり全部を片付けようとすると、うまくいかないので、まずは`SHOW CREATE TABLE`の問題から取り掛かっています。

**Comment by komainu8** [comment]
https://github.com/mysql/mysql-server/blob/mysql-8.0.23/sql/sql_show.cc#L1753 の `table_obj->foreign_keys()` で返される vector の長さが0なので、 `table_obj` に外部キーの情報が格納されていない。
`table_obj`自体は有効なアドレスを指していそうなので、`table_obj`自体はある。

**Comment by komainu8** [comment]
Mroongaのときは、 `table_obj->foreign_keys()` で返される vector の長さが`0`なので、`print_foreign_key_info`で情報が出力されない。
InnoDBのときは、 `table_obj->foreign_keys()` で返される vector の長さが`1`なので、情報が出力される。

`table_obj->foreign_keys()` で返される vector は ./sql/dd/impl/types/table.h の `m_foreign_keys`。
`m_foreign_keys`に値をセットしているのは、以下の2つ。

* `bool Table_impl::store_children(Open_dictionary_tables_ctx *otx)`
* `Foreign_key *Table_impl::add_foreign_key()`

関数名からして、 CREATE TABLE 時に呼び出されるのは、 `add_foreign_key` と推測。
この関数にブレイクポイントを設定して実行されるか見てみる。

**Comment by komainu8** [comment]
InnoDBでは、`fill_dd_foreign_keys_from_create_fields`で`add_foreign_key`を呼び出していて、ここで値を設定しているように見える。
一方、Mroongaでは、呼び出していない。

Mroongaを使っている場合、

```
  // Only add foreign key definitions for engines that support it.
  if (ha_check_storage_engine_flag(create_info->db_type,
                                   HTON_SUPPORTS_FOREIGN_KEYS)) {
    if (fill_dd_foreign_keys_from_create_fields(tab_obj, fk_keys, fk_keyinfo))
      return true;
  }
```

の `ha_check_storage_engine_flag`がfalseになる。
`create_info->db_type`が4096で`HTON_SUPPORTS_FOREIGN_KEYS`は2048。

2進数だと以下の通りで`HTON_SUPPORTS_FOREIGN_KEYS`のフラグが立ってないので外部キーの情報が記録されない。

```
4096:1000000000000
2048: 100000000000
```

**Comment by komainu8** [comment]
`HTON_SUPPORTS_FOREIGN_KEYS` はハンドラーの初期化のときに設定する。

InnoDBもそうしている。

```
  innobase_hton->flags = HTON_SUPPORTS_EXTENDED_KEYS |
                         HTON_SUPPORTS_FOREIGN_KEYS | HTON_SUPPORTS_ATOMIC_DDL |
                         HTON_CAN_RECREATE | HTON_SUPPORTS_SECONDARY_ENGINE |
                         HTON_SUPPORTS_TABLE_ENCRYPTION;
```

Mroongaは初期化のときにこのフラグを設定していないので、外部キーの情報が登録されない。

したがって、 `mrn_init`内で `hton->flags`に`HTON_SUPPORTS_FOREIGN_KEYS`をORすれば良い。

**Comment by komainu8** [comment]
修正を Pull request した。

`HTON_SUPPORTS_FOREIGN_KEYS`を設定することで、`information_schema`の該当のテーブルにも外部キーの情報が表示されるようになった。
