### ISSUE TITLE
mariadb-mroonga 4.09 on CentOS 7 causes "lost connection"

### ISSUE THREAD

**Issue by kenhys** [mroonga/mroonga#40]
mariadb 5.5.40-2がリリースされていたのでmariadb-mroonga-4.09-2のパッケージを用意したら
mysql -u root < /usr/share/mroonga/install.sqlでlost connectionが発生した。
INSTALL PLUGINしたときに発動する。

4.09-1に戻してみたが同じようだった。

* groonga 4.1.0 + mroonga 4.09-1 + mariadb 5.5.40-1 Lost connection
* groonga 4.1.0 + mroonga 4.09-2 + mariadb 5.5.40-2 Lost connection

[groonga-dev,03041] Re: MariaDBバンドル版Mroonga 4.09でMroongaがインストール出来ない問題について
と問題は同根だという話がある。
http://sourceforge.jp/projects/groonga/lists/archive/dev/2015-January/003042.html

**Comment by kenhys** [comment]
5.5.41のアップデートが2/5に出た。
http://vault.centos.org/7.0.1406/updates/Source/SPackages/mariadb-5.5.41-2.el7_0.src.rpm
g
https://mariadb.atlassian.net/browse/MDEV-7475 のパッチがあたっているかは未確認。

**Comment by kenhys** [comment]
MDEV-7475に対するパッチをあてることはしていないようだ。CentOS 7ではMariaDB 5.5.42待ちか。

**Comment by kou** [comment]
MariaDB 5.5.41以前ではMroonga側でこの機能を使わないようにしたので問題は起きない。
