### ISSUE TITLE
Percona Serverの依存関係の障害が出ています。

### ISSUE THREAD

**Issue by Yuutakasan** [mroonga/mroonga#402]
ご確認お願いします。

エラー: パッケージ: percona-server-57-mroonga-11.00-1.el7.x86_64 (@groonga-centos)
             要求: Percona-Server-client-57 = 5.7.32-35.1.el7
            削除中: Percona-Server-client-57-5.7.32-35.1.el7.x86_64 (@percona-release-x86_64)
                Percona-Server-client-57 = 5.7.32-35.1.el7
            次のものにより更新された: : Percona-Server-client-57-5.7.33-36.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.33-36.1.el7
            利用可能: Percona-Server-client-57-5.7.10-1rc1.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-1rc1.1.el7
            利用可能: Percona-Server-client-57-5.7.10-2rc2.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-2rc2.1.el7
            利用可能: Percona-Server-client-57-5.7.10-3.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.10-3.1.el7
            利用可能: Percona-Server-client-57-5.7.11-4.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.11-4.1.el7
            利用可能: Percona-Server-client-57-5.7.12-5.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.12-5.1.el7
            利用可能: Percona-Server-client-57-5.7.13-6.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.13-6.1.el7
            利用可能: Percona-Server-client-57-5.7.14-7.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.14-7.1.el7
            利用可能: Percona-Server-client-57-5.7.14-8.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.14-8.1.el7
            利用可能: Percona-Server-client-57-5.7.15-9.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.15-9.1.el7
            利用可能: Percona-Server-client-57-5.7.16-10.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.16-10.1.el7
            利用可能: Percona-Server-client-57-5.7.17-11.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-11.1.el7
            利用可能: Percona-Server-client-57-5.7.17-12.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-12.1.el7
            利用可能: Percona-Server-client-57-5.7.17-13.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.17-13.1.el7
            利用可能: Percona-Server-client-57-5.7.18-14.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-14.1.el7
            利用可能: Percona-Server-client-57-5.7.18-15.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-15.1.el7
            利用可能: Percona-Server-client-57-5.7.18-16.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.18-16.1.el7
            利用可能: Percona-Server-client-57-5.7.19-17.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.19-17.1.el7
            利用可能: Percona-Server-client-57-5.7.20-18.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-18.1.el7
            利用可能: Percona-Server-client-57-5.7.20-19.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.20-19.1.el7
            利用可能: Percona-Server-client-57-5.7.21-20.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-20.1.el7
            利用可能: Percona-Server-client-57-5.7.21-21.2.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.2.el7
            利用可能: Percona-Server-client-57-5.7.21-21.3.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.21-21.3.el7
            利用可能: Percona-Server-client-57-5.7.22-22.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.22-22.1.el7
            利用可能: Percona-Server-client-57-5.7.23-23.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-23.1.el7
            利用可能: Percona-Server-client-57-5.7.23-24.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-24.1.el7
            利用可能: Percona-Server-client-57-5.7.23-25.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.23-25.1.el7
            利用可能: Percona-Server-client-57-5.7.24-26.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-26.1.el7
            利用可能: Percona-Server-client-57-5.7.24-27.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.24-27.1.el7
            利用可能: Percona-Server-client-57-5.7.25-28.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.25-28.1.el7
            利用可能: Percona-Server-client-57-5.7.26-29.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.26-29.1.el7
            利用可能: Percona-Server-client-57-5.7.27-30.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.27-30.1.el7
            利用可能: Percona-Server-client-57-5.7.28-31.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.28-31.1.el7
            利用可能: Percona-Server-client-57-5.7.29-32.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.29-32.1.el7
            利用可能: Percona-Server-client-57-5.7.30-33.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.30-33.1.el7
            利用可能: Percona-Server-client-57-5.7.31-34.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-client-57 = 5.7.31-34.1.el7
エラー: パッケージ: percona-server-57-mroonga-11.00-1.el7.x86_64 (@groonga-centos)
             要求: Percona-Server-server-57 = 5.7.32-35.1.el7
            削除中: Percona-Server-server-57-5.7.32-35.1.el7.x86_64 (@percona-release-x86_64)
                Percona-Server-server-57 = 5.7.32-35.1.el7
            次のものにより更新された: : Percona-Server-server-57-5.7.33-36.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.33-36.1.el7
            利用可能: Percona-Server-server-57-5.7.10-1rc1.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-1rc1.1.el7
            利用可能: Percona-Server-server-57-5.7.10-2rc2.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-2rc2.1.el7
            利用可能: Percona-Server-server-57-5.7.10-3.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.10-3.1.el7
            利用可能: Percona-Server-server-57-5.7.11-4.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.11-4.1.el7
            利用可能: Percona-Server-server-57-5.7.12-5.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.12-5.1.el7
            利用可能: Percona-Server-server-57-5.7.13-6.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.13-6.1.el7
            利用可能: Percona-Server-server-57-5.7.14-7.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.14-7.1.el7
            利用可能: Percona-Server-server-57-5.7.14-8.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.14-8.1.el7
            利用可能: Percona-Server-server-57-5.7.15-9.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.15-9.1.el7
            利用可能: Percona-Server-server-57-5.7.16-10.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.16-10.1.el7
            利用可能: Percona-Server-server-57-5.7.17-11.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-11.1.el7
            利用可能: Percona-Server-server-57-5.7.17-12.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-12.1.el7
            利用可能: Percona-Server-server-57-5.7.17-13.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.17-13.1.el7
            利用可能: Percona-Server-server-57-5.7.18-14.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-14.1.el7
            利用可能: Percona-Server-server-57-5.7.18-15.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-15.1.el7
            利用可能: Percona-Server-server-57-5.7.18-16.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.18-16.1.el7
            利用可能: Percona-Server-server-57-5.7.19-17.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.19-17.1.el7
            利用可能: Percona-Server-server-57-5.7.20-18.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-18.1.el7
            利用可能: Percona-Server-server-57-5.7.20-19.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.20-19.1.el7
            利用可能: Percona-Server-server-57-5.7.21-20.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-20.1.el7
            利用可能: Percona-Server-server-57-5.7.21-21.2.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.2.el7
            利用可能: Percona-Server-server-57-5.7.21-21.3.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.21-21.3.el7
            利用可能: Percona-Server-server-57-5.7.22-22.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.22-22.1.el7
            利用可能: Percona-Server-server-57-5.7.23-23.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-23.1.el7
            利用可能: Percona-Server-server-57-5.7.23-24.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-24.1.el7
            利用可能: Percona-Server-server-57-5.7.23-25.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.23-25.1.el7
            利用可能: Percona-Server-server-57-5.7.24-26.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-26.1.el7
            利用可能: Percona-Server-server-57-5.7.24-27.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.24-27.1.el7
            利用可能: Percona-Server-server-57-5.7.25-28.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.25-28.1.el7
            利用可能: Percona-Server-server-57-5.7.26-29.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.26-29.1.el7
            利用可能: Percona-Server-server-57-5.7.27-30.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.27-30.1.el7
            利用可能: Percona-Server-server-57-5.7.28-31.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.28-31.1.el7
            利用可能: Percona-Server-server-57-5.7.29-32.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.29-32.1.el7
            利用可能: Percona-Server-server-57-5.7.30-33.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.30-33.1.el7
            利用可能: Percona-Server-server-57-5.7.31-34.1.el7.x86_64 (percona-release-x86_64)
                Percona-Server-server-57 = 5.7.31-34.1.el7

**Comment by komainu8** [comment]
ご報告ありがとうございます！

https://github.com/mroonga/mroonga/commit/0da6c89dc0d8f7d54db21a19c7aed833da3e4ded にて対応しました。  
今日か明日リリース予定のMroonga 11.01で直ります。

**Comment by Yuutakasan** [comment]
了解しました！ありがとうございます。
