### ISSUE TITLE
ドキュメント: MATCH AGAINSTではBOOLEAN MODEを使うようにする

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#41]
多くの場合でBOOLEAN MODEの方が使い勝手がよいドキュメントでも `MATCH (column) AGAINST ("+XXX +YYY" IN BOOLEAN MODE)` を使うようにする。

**Comment by kenhys** [comment]
* doc/source/tutorial/wrapper.rst 
* doc/source/reference/full_text_search/scoring.rst
にBOOLEAN MODEを使っていない部分が残っている

**Comment by kenhys** [comment]
doc/source/reference/full_text_search/scoring.rst はin natural language modeの説明なのでそのままでよい
