### ISSUE TITLE
Percona-Server アップデートに失敗

### ISSUE THREAD

**Issue by Yuutakasan** [mroonga/mroonga#429]
groonga-libs-11.0.4-1.el7.x86_64の依存性の解決に失敗します。
対応お願いいします。

--> トランザクションの確認を実行しています。
---> パッケージ groonga-libs.x86_64 0:11.0.4-1.el7 を アップデート
--> 依存性の処理をしています: arrow-libs = 4.0.0 のパッケージ: groonga-libs-11.0.4-1.el7.x86_64
---> パッケージ td-agent-bit.x86_64 0:1.7.9-1 を インストール
--> 依存性解決を終了しました。
--> トランザクションの確認を実行しています。
---> パッケージ groonga-libs.x86_64 0:11.0.4-1.el7 を アップデート
--> 依存性の処理をしています: arrow-libs = 4.0.0 のパッケージ: groonga-libs-11.0.4-1.el7.x86_64
---> パッケージ kernel.x86_64 0:3.10.0-1127.19.1.el7 を 削除
---> パッケージ kernel-devel.x86_64 0:3.10.0-1127.19.1.el7 を 削除
--> 依存性解決を終了しました。
エラー: パッケージ: groonga-libs-11.0.4-1.el7.x86_64 (groonga-centos)
             要求: arrow-libs = 4.0.0
            削除中: arrow-libs-2.0.0-1.el7.x86_64 (@groonga-centos)
                arrow-libs = 2.0.0-1.el7
            次のものにより更新された: : arrow-libs-4.0.1-1.el7.x86_64 (groonga-centos)
                arrow-libs = 4.0.1-1.el7
            削除中: arrow-libs-3.0.0-1.el7.x86_64 (installed)
                arrow-libs = 3.0.0-1.el7
            次のものにより更新された: : arrow-libs-4.0.1-1.el7.x86_64 (groonga-centos)
                arrow-libs = 4.0.1-1.el7
            利用可能: arrow-libs-0.3.1.20170506-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.3.1.20170506-1.el7.centos
            利用可能: arrow-libs-0.3.1.20170508-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.3.1.20170508-1.el7.centos
            利用可能: arrow-libs-0.3.1.20170510-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.3.1.20170510-1.el7.centos
            利用可能: arrow-libs-0.3.1.20170512-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.3.1.20170512-1.el7.centos
            利用可能: arrow-libs-0.3.1.20170517-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.3.1.20170517-1.el7.centos
            利用可能: arrow-libs-0.4.1.20170524-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.4.1.20170524-1.el7.centos
            利用可能: arrow-libs-0.5.0.20170612-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.5.0.20170612-1.el7.centos
            利用可能: arrow-libs-0.6.0.20170726-1.el7.centos.x86_64 (groonga-centos)
                arrow-libs = 0.6.0.20170726-1.el7.centos
            利用可能: arrow-libs-4.0.0-1.el7.x86_64 (groonga-centos)
                arrow-libs = 4.0.0-1.el7

**Comment by komainu8** [comment]
ご報告ありがとうございます！
確認して対応します。対応完了したら、こちらでお知らせします。

**Comment by kou** [comment]
`arrow-libs = 4.0.0-1.el7`という依存関係になっていないのが悪いのかも。

**Comment by komainu8** [comment]
こちらですが、 https://github.com/groonga/groonga/pull/1199 にて修正済みでした。
ただ、お使いの環境には、すでに`arrow-libs-4.0.1`が入っているようです。

groonga-libs 11.0.4 が要求するのは、`arrow-libs-4.0.0`なので、すでにシステムに入っている`arrow-libs`のバージョンと
groonga-libsが要求する`arrow-libs`のバージョンが異なるためエラーになっています。

https://github.com/groonga/groonga/pull/1199 以降は、groonga-libsが要求するバージョンが依存パッケージとして入るのですが、前述の修正が入る前のバージョンは、そのパッケージがインストールされたときの最新のバージョンを取ってきてしまうため、groonga-libsが要求するバージョンと異なるバージョンの`arrow-libs`がインストールされる可能性があります。

対処方法ですが、今月末にリリース予定のGroongaでは、`arrow-libs-4.0.1`を要求するようにしたので、今月末のリリース後にアップデートするのが良いと思います。

**Comment by Yuutakasan** [comment]
@komainu8 こちらバージョンアップが適切に実施できる事を確認しました。ありがとうございました！

**Comment by komainu8** [comment]
良かったです！
