### ISSUE TITLE
Percona 8.0.25-15.1.el8への対応について

### ISSUE THREAD

**Issue by YoyaYOSHIDA** [mroonga/mroonga#431]
`percona-server-server-8.0.25-15.1.el8`への対応よろしくお願いいたします。
以下、参考までに当該バージョンで`percona-server-8.0-mroonga`をインストールしようとした際の出力です。

```bash
[***@*** ~]# dnf install percona-server-8.0-mroonga 
メタデータの期限切れの最終確認: 0:09:29 時間前の 2021年07月20日 16時17分10秒 に実施しました。
依存関係が解決しました。
===
 パッケージ アーキテクチャー バージョン リポジトリー サイズ
===
インストール:
 percona-server-8.0-mroonga x86_64 11.04-1.el8 groonga-centos 268 k
依存関係のインストール:
 groonga-normalizer-mysql x86_64 1.1.4-1.el8 groonga-centos 58 k
ダウングレード:
 percona-server-client x86_64 8.0.23-14.1.el8 ps-80-release-x86_64 12 M
 percona-server-server x86_64 8.0.23-14.1.el8 ps-80-release-x86_64 49 M
トランザクションの概要
===
インストール 2 パッケージ
ダウングレード 2 パッケージ
```

**Comment by komainu8** [comment]
ご報告ありがとうございます！
対応中です。もう少々おまちください！

**Comment by komainu8** [comment]
このIssuesの依存関係のエラーについては対応しましたが、  #429 が直らないとこのIssuesとは別の箇所でインストールに失敗するので、 #429 を修正してからこのIssuesをCloseします。

**Comment by komainu8** [comment]
#429 はすでに修正済みでした。現在は` percona-server-8.0`向けのパッケージのインストールができるようになっていると思いますので、ご確認いただければと思います。

**Comment by komainu8** [comment]
@YoyaYOSHIDA こちらインストールできるようになっているはずですので、ご確認いただければと思います。

**Comment by YoyaYOSHIDA** [comment]
@komainu8 ご対応いただきありがとうございます。早速利用させていただきます🙏

**Comment by YoyaYOSHIDA** [comment]
いったんこちらのIssueは閉じさせていただきます。ご対応ありがとうございました。
