### ISSUE TITLE
spatialインデックスを張ったpointが取得できない

### ISSUE THREAD

**Issue by qp3pckg** [mroonga/mroonga#452]
**参考**
- https://mroonga.org/ja/docs/install/centos.html#centos-7-with-mariadb-10-5-package
- https://mroonga.org/ja/docs/tutorial/storage.html#how-to-use-geolocation-search

**検証環境:** CentOS7
1. OSインストール
2. SELinuxを切る
3. yum update
4. リブート
5. ドキュメントの「2.5.8. CentOS 7（MariaDB 10.5のパッケージを利用）」に記載されている手順をすべて実行する
6. mysqlに入る
7. create database で適当なDBを作る
8. use で作ったDBに入る
9. ドキュメントの「4.3.7. 位置情報検索の利用方法」に記載されている手順をすべて実行する

上記の手順の最後
```
SELECT id, name, AsText(location)
  FROM shops
 WHERE MBRContains(GeomFromText('LineString(139.7101 35.7292, 139.7662 35.6815)'), location);
```
がEmptyを返します。
ちなみにspacialインデックスを外したら取得できました。

**Comment by kou** [comment]
うーん、今にして思えば、SRIDが指定されていない場合（MySQL 5.7以前の場合はすべて）は挙動を変えずに経度緯度で値を受取、MySQL 8.0以降でSRID 4326を明示的に指定されたときだけ緯度経度として扱うようにしたほうがよかったかも。。。失敗したな。。。もう戻せないけど。。。
