### ISSUE TITLE
Outdated instructions to install from source

### ISSUE THREAD

**Issue by perrinjerome** [mroonga/mroonga#509]
In https://mroonga.org/docs/install/others.html#mysql-u-root-install-sql we can read:

> You need to run some SQLs to register Mroonga to MySQL such as `INSTALL PLUGIN` and `CREATE FUNCTION`. They are written in `${PREFIX}/share/mroonga/install.sql`.
>
> Here is an example when you specify `--prefix=$HOME/local` to `configure`:
>
>```
>% mysql -u root < $HOME/local/share/mroonga/install.sql
>```

but since 12.04 ( https://github.com/mroonga/mroonga/commit/35f593037c2d8f5a497349ff98f3a3ce31ee95de ) it is also required to run `update.sql`.

If it's possible to keep the current behavior of using only `install.sql`, I'm sure people packaging mroonga will appreciate ;)

Thanks

**Comment by komainu8** [comment]
@perrinjerome 
Thank you for your report.

I'm fixing that we don't require `update.sql` when the update and manual install for Mroonga at https://github.com/mroonga/mroonga/pull/511.

**Comment by perrinjerome** [comment]
@komainu8 @kou I wanted to confirm that with the just released mroonga 12.0.7 everything is fine regarding this and to thank you one more time 👍

**Comment by kou** [comment]
That's good to know! :-)
