### ISSUE TITLE
install.sql in mysql-community-8.0-mroonga 12.06-1 for bullseye is broken

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#520]
```console
$ cat /usr/share/mroonga/install.sql 
source @MRN_DATA_DIR@/install_plugin.sql
source @MRN_DATA_DIR@/update.sql
```

**Comment by komainu8** [comment]
CIで検出できなかったのは、Debian bullseye の mysql-community-8.0-mroonga 向けのパッケージのときはUpgradeのテストが動いてなかったため。https://github.com/mroonga/mroonga/pull/522 の修正でCIで検出可能になるはず。

ただ、 https://github.com/mroonga/mroonga/pull/522 がちゃんと動くか確認するためには、 先に https://github.com/mroonga/mroonga/pull/521 を解決する必要がある。
