### ISSUE TITLE
install.sql was broken

### ISSUE THREAD

**Issue by tomop-tg** [mroonga/mroonga#525]
I merged Mroonga 12.06 and Groonga 12.0.6 into MariaDB 10.6.9 source tree and built it.

`/usr/` is missing from the path in install.sql.

```
$ cat /usr/share/mysql/mroonga/install.sql
source share/mysql/mroonga/install_plugin.sql
source share/mysql/mroonga/update.sql
```

**Comment by komainu8** [comment]
@tomop-tg Thank you for your report.
I'll deal with this problem.
