### ISSUE TITLE
mroonga_highlight_html の挿入タグ

### ISSUE THREAD

**Issue by xakuro** [mroonga/mroonga#537]
mroonga_highlight_html の挿入タグを任意で指定できる（`<mark class="keyword">` など）ように対応をお願いします。

**Comment by xakuro** [comment]
すみません、確認不足でした。閉じます。

**Comment by komainu8** [comment]
あ、すみません。
#539 はまだ作業中で @xakuro  さんと @kou さんのやりとりをもとに、昨日着手したばかりです。
まだ、マージされるような段階ではないので、 #539 がマージてからこのIssueも閉じたいのでReopenします。。

誤解を与えてしまったようですみません。。。
