### ISSUE TITLE
Does it have power off protection function?

### ISSUE THREAD

**Issue by 277801235** [mroonga/mroonga#541]
My table, it was disabled after a power outage and reboot.
The error message is as follows:
SQLSTATE[HY000]: General error: 1016 mroonga: failed to open table: <ydisk_fileindex>

**Comment by komainu8** [comment]
No, Mroonga doesn't have power off protection function.
Mroonga isn't crash safe now.

Therefore, we need to execute reconstruct Mroonga's indexes in your case.

**Comment by 277801235** [comment]
Thank you for response.
Can I reconstruct  Mroonga's indexes without dropping the table?
How do I operate it?

**Comment by kou** [comment]
We can use `ALTER TABLE ... DISABLE KEYS` and then `ALTER TABLE ... ENABLE KEYS` to recreate indexes.

**Comment by 277801235** [comment]
I tried, but there were errors:
```
ALTER TABLE `ydisk_fileIndex` DISABLE KEYS;
> 1016 - mroonga: failed to open table: <ydisk_fileindex>
```

**Comment by 277801235** [comment]
> We can use `ALTER TABLE ... DISABLE KEYS` and then `ALTER TABLE ... ENABLE KEYS` to recreate indexes.

I tried, but there were errors:
```
ALTER TABLE `ydisk_fileIndex` DISABLE KEYS;
> 1016 - mroonga: failed to open table: <ydisk_fileindex>
```

**Comment by kou** [comment]
Could you show `groonga.log` in MySQL's data directory?

**Comment by kou** [comment]
Ah, you're on Windows.
It seems that you can't repair your data from this situation...
You can use Mroonga again by:

1. Drop all Mroonga tables
2. Stop MariaDB
3. Remove all "ydisk.mrn*" files in MariaDB's data directory
4. Start MariaDB
5. Create Mroonga tables again

**Comment by 277801235** [comment]
> Ah, you're on Windows. It seems that you can't repair your data from this situation... You can use Mroonga again by:
> 
> 1. Drop all Mroonga tables
> 2. Stop MariaDB
> 3. Remove all "ydisk.mrn*" files in MariaDB's data directory
> 4. Start MariaDB
> 5. Create Mroonga tables again

When I try to drop the table:
```
MariaDB [ydisk]> drop table ydisk_fileIndex;
ERROR 145 (HY000): [table][cursor][open] table must not be NULL
```

**Comment by kou** [comment]
`select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY'); drop table ydisk_fileIndex;` may work.

> So, I skipped step 1 and remove "ydisk_fileIndex.frm" file then it works.
> Is that the right way?

It may work. :-)

**Comment by 277801235** [comment]
> 

```
MariaDB [ydisk]> select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY');
ERROR 1305 (42000): FUNCTION ydisk.mroonga_command does not exist
```

**Comment by 277801235** [comment]
> `select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY'); drop table ydisk_fileIndex;` may work.
> 
> > So, I skipped step 1 and remove "ydisk_fileIndex.frm" file then it works.
> > Is that the right way?
> 
> It may work. :-)

```
MariaDB [ydisk]> select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY');
ERROR 1305 (42000): FUNCTION ydisk.mroonga_command does not exist
```

**Comment by 277801235** [comment]
> `select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY'); drop table ydisk_fileIndex;` may work.
> 
> > So, I skipped step 1 and remove "ydisk_fileIndex.frm" file then it works.
> > Is that the right way?
> 
> It may work. :-)


```
MariaDB [ydisk]> CREATE FUNCTION mroonga_command RETURNS STRING SONAME 'ha_mroonga';
Query OK, 0 rows affected (0.003 sec)

MariaDB [ydisk]> select mroonga_command('table_create ydisk_fileIndex TABLE_NO_KEY');
ERROR 1026 (HY000): system error[80]: 文件存在。: CreateFile(<ydisk.mrn.0000100>, <O_RDWR|O_CREAT|O_EXCL>) failed
```

**Comment by kou** [comment]
You don't need to run `mroonga_command` because you already removed `.frm`.

**Comment by 277801235** [comment]
> You don't need to run `mroonga_command` because you already removed `.frm`.

Thanks a lot!
