### ISSUE TITLE
[Bug]: 複合主キーを設定したテーブルに対するレコードの更新に失敗します

### ISSUE THREAD

**Issue by handmound** [mroonga/mroonga#592]
### What happend?

ストレージエンジンにMroongaを指定したテーブルに複合主キーを設定していると、
レコードの更新に失敗してしまいます。

### How to reproduce it

以下のようなテーブルがあったとします。

```sql
CREATE TABLE tbl_work (
  cid char(10) NOT NULL,
  fid char(10) NOT NULL,
  title varchar(200) NOT NULL,
  content longtext,
  PRIMARY KEY (cid, fid),
  FULLTEXT INDEX search_fidx (title, content) COMMENT 'normalizer "NormalizerAuto"'
) ENGINE = Mroonga DEFAULT CHARSET utf8;
```

上記テーブルに対してレコードの更新を行うと、以下の通りエラーとなってしまいます。

```text
mysql> INSERT INTO tbl_work (cid, fid, title) VALUES ('C000001234', '0000001011', 'テスト登録');
Query OK, 1 row affected (0.00 sec)

mysql> UPDATE tbl_work SET content='test' WHERE cid='C000001234' AND fid='0000001011';
ERROR 1265 (01000): data truncated for primary key column: <cid>
mysql>
```

### Expected behavior

テーブル作成時に全文検索のインデックス指定を除外しても状況変わらず、
ストレージエンジンにMyISAMを指定した同一構造のテーブルでは問題ありません。
複合主キーを外すと正常に更新できる状況です。

### Environment

- OS: Red Hat Enterprise Linux
- OS Version: 8.6
- DB: MySQL
- DB Version: 8.0.31-1
- Mroonga Version: 12.10

**Comment by kou** [comment]
実装をよく見たらそもそもサポートしていませんでした。。。

プライマリーキーのカラムを変更するのをサポートするのは大変ですが、このケースはプライマリーキーじゃないカラムなのでサポートしたいですね。

**Comment by handmound** [comment]
お手数おかけします。MySQL5.7、Mroonga10.11からの移行ですが、移行元の環境では更新できる状況です。

**Comment by kou** [comment]
実装しました。

ところで、Mroongaは新規ユーザーを増やすために事例を集めている https://mroonga.org/ja/users/ のですが、もしよければ事例提供をご検討ください。

**Comment by handmound** [comment]
お忙しい中、早速のご対応ありがとうございます。お恥ずかしながら、修正いただいた内容の適用方法が分かりません。
次期リリースに含まれる感じでしょうか(mysql-community-8.0-mroongaのアップデートで対応)？それともソースから
コンパイルし、再インストールが必要でしょうか？

**Comment by komainu8** [comment]
@handmound はい。次のリリース(Mroonga version 12.12)に含まれます。次のリリースは今月末を予定しています。
リリース後に dnf で mysql-community-8.0-mroonga パッケージをアップデートしていただければと思います。（ソースからのコンパイル->インストールは不要です。）

**Comment by handmound** [comment]
ありがとうございます。Ver.12.12のリリースを待って適用後、動作確認したいと思います。お手数をおかけしました。

**Comment by kou** [comment]
リリース前に https://github.com/mroonga/mroonga/actions/runs/3948996741 にある`packages-mysql-community-8.0-almalinux-8`内にあるRPMを使って確認することもできます。

**Comment by komainu8** [comment]
@handmound こちらの問題を修正したMroonga 12.12をリリースしましたので、動作確認いただければと思います。

**Comment by handmound** [comment]
@kou @komainu8 早速アップデートし確認したところ、問題なく動作しました。この度はありがとうございました。このような場の作法もわからず質問しており、大変恐縮ですが、今後ともよろしくお願いいたします。

**Comment by komainu8** [comment]
良かったです！
また、なにかありましたらお気軽にお問い合わせください。
