### ISSUE TITLE
Document about how to use Mroonga on Travis CI

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#61]
`sudo: required` should be described.

**Comment by kenhys** [comment]
http://groonga.org/ja/docs/development/travis-ci.html みたいに開発者向け情報の配下に追加するとよい。

**Comment by komainu8** [comment]
Mroongaは既にTravis CIを使ってないのでCloseする。

**Comment by kou** [comment]
これはMroonga開発者がどうTravis CIを使うかという話ではなくて、MroongaユーザーがTravis CIでMroongaを使うためのドキュメントを書くというやつです。

なのでMroongaがTravis CIを使っているかどうかは関係ないです。

**Comment by komainu8** [comment]
そうだったのですね。。。開発者向け情報の下に追加とあったので、開発者がTravisCIをどう使うかという話だと勘違いしました。。。

**Comment by kou** [comment]
https://groonga.org/ja/docs/development.html
ここの「開発者」はGroongaの開発者じゃなくてGroongaを使ってアプリケーションを開発している開発者なんですよ。

https://groonga.org/ja/docs/contribution/development.html
Groongaの開発者はこっち。

**Comment by komainu8** [comment]
おぉ。。。なるほど！理解しました。ありがとうございます！
