### ISSUE TITLE
doc: follow parameter name change

### ISSUE THREAD

**Issue by myokoym** [mroonga/mroonga#63]
See http://mroonga.org/ja/docs/news.html#release-5-04
- `parser` -> `tokenizer`
- `index_flags` -> `flags`
- `type` -> `groonga_type`

For example: http://mroonga.org/ja/docs/tutorial/storage.html#how-to-specify-the-parser-for-full-text-search

**Comment by kenhys** [comment]
index_flags and type are fixed.

COMMENT parser is used:
doc/source/reference/sql_commands.rst
doc/source/reference/server_variables.rst
