### ISSUE TITLE
[groonga-dev,03332] Mroonga5.04でSELECT結果が0行になる

### ISSUE THREAD

**Issue by kou** [mroonga/mroonga#65]
http://osdn.jp/projects/groonga/lists/archive/dev/2015-July/003334.html

**Comment by kou** [comment]
@myokoym Are you still working on this issue? Can I try to fix it?

**Comment by myokoym** [comment]
I'm not working on this. Please try to fix it.
Current status is that I reproduced this issue by this test: https://github.com/myokoym/mroonga/commit/a4eef459b483833c11112f3ea1813b37524a82ab

**Comment by kou** [comment]
I used your test. Thanks.
