### ISSUE TITLE
doc: update `How to contribute in documentation topics` using CMake commands

### ISSUE THREAD

**Issue by otegami** [mroonga/mroonga#707]
ref: https://github.com/mroonga/mroonga/issues/695

### What is your problem?

We will drop using `GNU Autotools` in near future. We should update documentation using `CMake`.

###  How we will update the documentation.

For example, we will update the following commands using `CMake` instead of `GNU Autotools`.

Before
```console
% ./autogen.sh
% ./configure --enable-document --with-mysql-source=(SOURCE_DIRECTORY_OF_MySQL)
```

After
```console
% cmake -S . -B ../mroonga.doc --preset=doc \
                               -DCMAKE_INSTALL_PREFIX=/tmp/local \
                               -DMYSQL_SOURCE_DIR=~/work/cpp/mysql-8.4.0 \
                               -DMYSQL_BUILD_DIR=~/work/cpp/mysql-8.4.0.build \
                               -DMYSQL_CONFIG=/tmp/local/bin/mysql_config
```

## Update content lists

About [`8.3. How to contribute in documentation topics`](https://mroonga.org/docs/contribution/documentation.html)
- [x] Convert the document's format from reST to md
- [x] 8.3.1.1. Required softwares
- [x] 8.3.1.5. Initial configuration for building documentation
- ~~[ ] 8.3.3.1. Create working branch~~ <- It has already been fixed by converting reST to md.
- [ ] 8.3.3.3. Confirm generated document

**Comment by otegami** [comment]
セクションごとに PR を作る形で進めていきます。
作業的には、作成した PR がマージされてから次のセクションに取り掛かる。

**Comment by otegami** [comment]
>  8.3.1.1. Required softwares

セクションの位置をずらして、`gem gettext` をインストールするフローを入れたい。
- https://mroonga.org/docs/contribution/documentation.html#required-softwares

**Comment by otegami** [comment]
@kou 
`reStructuredText` で書くのに慣れていないので、`Groonga` のときと同様に `Markdown` に変更しても良いでしょうか?
- https://github.com/groonga/groonga/pull/1742

**Comment by kou** [comment]
いいっすよ。

**Comment by otegami** [comment]
ありがとうございます！その方針で進めていきます。

**Comment by otegami** [comment]
> Convert the document's format from reST to md

**Comment by otegami** [comment]
```console
$ cmake --list-presets
CMake Error: Could not read presets from /home/kodama/work/cpp/mroonga: Invalid preset
```

**Comment by otegami** [comment]
```console
$ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ git diff
diff --git a/CMakePresets.json b/CMakePresets.json
index 244581d29..d9783c3e9 100644
--- a/CMakePresets.json
+++ b/CMakePresets.json
@@ -1,5 +1,5 @@
 {
-  "version": 1,
+  "version": 3,
   "cmakeMinimumRequired": {
     "major": 3,
     "minor": 19,
$ cmake --list-presets
Available configure presets:

  "doc" - For documentation
```

**Comment by otegami** [comment]
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

利用している `CMake` のバージョンによって変更する必要がありそう。
リポジトリ側で提供する `version` は、利用できる最も低いバージョンに合わせておくのが良いのかな？
ちょっと聞こう。

**Comment by komainu8** [comment]
https://github.com/mroonga/mroonga/blob/main/CMakeLists.txt#L36 に合わせるのが良いのでは。

**Comment by otegami** [comment]
ありがとうございます。
`cmake-presets` の機能が使えるのが、CMake v3.19 からなので、 v3.16 は利用できないのです。

**Comment by otegami** [comment]
CMakePresets の問題は解決済み
- https://github.com/mroonga/mroonga/pull/716

**Comment by otegami** [comment]
> 8.3.1.1. Required softwares

次はこのセクションを更新していく
現状は TODO なので、`gem gettext` のインストールをまず追加したい。

**Comment by otegami** [comment]
レビュー対応をしていく
