### ISSUE TITLE
doc: update `Others` using CMake commands

### ISSUE THREAD

**Issue by otegami** [mroonga/mroonga#710]
ref: https://github.com/mroonga/mroonga/issues/695

### What is your problem?

We want to use `CMake` instead of `GNU Autotools`. That's why we should update documentation.

## Update content lists

About [`2.11. Others`](https://mroonga.org/docs/install/others.html)

- [x] 2.11.1.3. MySQL
- [ ] 2.11.2. Build from source
- [ ] 2.11.2.1.1. --with-mysql-source=PATH
- [ ] 2.11.2.1.2. --with-mysql-build=PATH
- [ ] 2.11.2.1.3. --with-mysql-config=PATH
- [ ] 2.11.2.1.4. --with-default-tokenizer=TOKENIZER
- [ ] 2.11.2.1.5. --prefix=PATH
- [ ] 2.11.2.1.6. PKG_CONFIG_PATH=PATH
- [ ] 2.11.2.2. make
- [ ] 2.11.2.3. make install

**Comment by otegami** [comment]
こちらを進めていく。

**Comment by otegami** [comment]
reST から Markdown 形式に変更する。
なぜなら、複数のセクションを更新する必要があり、なれていない reST 形式だと本質の部分以外に時間を使ってしまう可能性があるため

**Comment by otegami** [comment]
> 2.11.1.3. MySQL

`make` を使ったビルドから `CMake with Ninja` を利用した方法に更新する。
なぜなら、`make` を導入する必要もなく、早くビルドが終わって嬉しいと思ったため

**Comment by komainu8** [comment]
> > 2.11.1.3. MySQL
> 
> `make` を使ったビルドから `CMake with Ninja` を利用した方法に更新する。 なぜなら、`make` を導入する必要もなく、早くビルドが終わって嬉しいと思ったため

MySQLのソースのビルドにNinjaって使えましたっけ？

**Comment by komainu8** [comment]
https://dev.mysql.com/doc/refman/8.4/en/installing-source-distribution.html
https://github.com/mysql/mysql-server/blob/527c12ed611f3fe072c3043734319edb2c733099/Docs/README.build#L87

公式のビルド手順では`make`を使っているようです。

**Comment by kou** [comment]
Ninjaでビルドできます。

**Comment by otegami** [comment]
CMake with Ninja でビルドできそうです。
- https://github.com/mysql/mysql-server/tree/8.4/Docs

**Comment by komainu8** [comment]
> Ninjaでビルドできます。
> CMake with Ninja でビルドできそうです。

おぉ。知りませんでした。ありがとうございます。

**Comment by otegami** [comment]
MySQL のビルドステップのドキュメント更新を行う。
