### ISSUE TITLE
Fail build package for Mroonga with MariaDB 10.6 on Ubuntu 22.04

### ISSUE THREAD

**Issue by komainu8** [mroonga/mroonga#718]
### What happend?

Fail build package on CI as below.

https://github.com/mroonga/mroonga/actions/runs/9592743906/job/26451925575

### How to reproduce it

We execute the following command on CI environment equivalent.

```
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-mysql-source=mariadb-10.6-10.6.18 --with-mysql-build=mariadb-10.6-10.6.18/builddir --with-mysql-config=mariadb-10.6-10.6.18/builddir/scripts/mysql_config
```

### Expected behavior

The build of package success.

### Environment

- OS: Ubuntu
- OS Version: Ubuntu 22.04 LTS
- DB: MariaDB
- DB Version: 10.6.18
- Mroonga Version: 14.0.4
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-version
- libgroonga Version: 14.0.4
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-libgroonga-version

**Comment by komainu8** [comment]
ビルド失敗の原因は、 https://github.com/mroonga/mroonga/actions/runs/9589781806/job/26444177399#step:11:6075 かもしれない。

**Comment by komainu8** [comment]
mariadb-10.6-10.6.18 というディレクトリーが見つからない。
https://github.com/mroonga/mroonga/actions/runs/9592743906/job/26451925575#step:11:12594

**Comment by komainu8** [comment]
ちゃんとビルドできているとき。
https://github.com/mroonga/mroonga/actions/runs/9578206012/job/26408042030#step:11:5889

**Comment by komainu8** [comment]
問題の箇所がどこのスクリプトで動いているかをピンポイントで探そうとしていたが、無理そうなので、ちゃんと最初から処理を追っていこう。

**Comment by komainu8** [comment]
mroonga.clean/packages/mariadb-10.6-mroonga/apt/ubuntu-jammy/Dockerfile が動く。
それが、 https://github.com/mroonga/mroonga/actions/runs/9592743906/job/26451925575#step:11:3884 まで。

**Comment by komainu8** [comment]
次に `build.sh` が動く。
`build.sh`は`arrow/dev/tasks/linux-packages/apt/build.sh`のこと。

**Comment by komainu8** [comment]
目で追いかけるより、一回`build.sh`で`set -ux`して手元で実行してみてなんのコマンドを実行しているかを見たほうが速そう。

**Comment by komainu8** [comment]
なるほど。
`mariadb-10.6_10.6.16.orig.tar.gz`を解凍すると`mariadb-10.6-10.6.16/`、`mariadb-10.6_10.6.18.orig.tar.gz`を解凍すると`mariadb-10.6.18/`になって、解凍後のディレクトリー名が10.6.16のときと異なるので失敗する。

**Comment by komainu8** [comment]
これは意図した変更なのかどうか確認しよう。

**Comment by komainu8** [comment]
https://mariadb.org/download/ でソースアーカイブをダウンロードしたところ`mariadb-10.6.16`と`mariadb-10.6.18`というディレクトリー名だった。
なので、`mariadb-10.6-10.6.16`という名前はUbuntu向けのパッケージを作るときに変更していたと考えられる。
アップストリームと同じ名前に揃えたということだろう。

**Comment by komainu8** [comment]
ちがった。
発生しているのは、`run debuild "${debuild_options[@]}" "${dpkg_buildpackage_options[@]}"`の中だった。
`${PACKAGE}`は`mariadb-10.6-mroonga`だった。

**Comment by komainu8** [comment]
#722 の修正でビルドは通るようになる。
ただ、Launchpad上にアップロードするパッケージはリリースし直さないと更新できない。
（#722 の修正でソースアーカイブが変わってしまうので、リビルドできない。(ソースアーカイブをLaunchpadにアップロードできない)）

**Comment by komainu8** [comment]
6/29に他のプロダクトと合わせてリリースしよう。

**Comment by kou** [comment]
#722 の変更は`debian/`だけの変更で、ソースアーカイブは既存のやつでいいから`UBUNTU_MINOR_VERSION=2`とかでリリースできるよ。
