### ISSUE TITLE
ci linux build: update mysql-community-8.x packages 

### ISSUE THREAD

**Issue by otegami** [mroonga/mroonga#729]
### What happend?

CI has failed because new version of MySQL Community Server has just released.
- 8.4 LTS, 8.0.38 : https://dev.mysql.com/downloads/mysql/

Debian bookworm
```
  The following packages have unmet dependencies:
   mysql-community-8.0-mroonga : Depends: mysql-community-server (= 8.0.37-1debian12) but it is not going to be installed
                                 Depends: mysql-community-server-core (= 8.0.37-1debian12) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.
```
ref: https://github.com/mroonga/mroonga/actions/runs/9739127636/job/26873873332?pr=723

Ubuntu jammy
```
  The following packages have unmet dependencies:
   mysql-community-8.0-mroonga : Depends: mysql-community-server (= 8.0.37-1debian12) but it is not going to be installed
                                 Depends: mysql-community-server-core (= 8.0.37-1debian12) but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.
```
ref: https://github.com/mroonga/mroonga/actions/runs/9739127636/job/26873873332?pr=723

AlmaLinux 8/9
```
error: Failed build dependencies:
	mysql-community-devel = 8.0.37-1.el9 is needed by mysql-community-8.0-mroonga-14.05-1.el9.x86_64
```
ref: https://github.com/mroonga/mroonga/actions/runs/9739127636/job/26873873104?pr=723

### How to reproduce it

Re-run CI: https://github.com/mroonga/mroonga/actions/runs/9739127636/job/26873873104?pr=723

### Expected behavior

Find a dependent package. CI passed.

### Environment

- OS: Debian(bookwarm), Ubuntu(jammy), AlmaLinux8/9
- DB: MySQL Community
- DB Version: 8.4.0.1, 8.0.39
- Mroonga Version: [14.0.4]

**Comment by kou** [comment]
For Debian/Ubuntu: We need to rebuild our packages because our build configuration always uses the latest MySQL version when we build.

For AlmaLinux: We need to update MySQL version in our `.spec` like fe724bcb6ee7620debf90eb96ceb6f971a4f9ce5 and rebuild.
