### ISSUE TITLE
Spatial index is not used on MariaDB (10.1.8, 10.0.21) when queried

### ISSUE THREAD

**Issue by the-dunnock** [mroonga/mroonga#73]
Hi,

Spoke with MariaDB team who should I report first so we came to conclusion that I'll get in touch with you and if this bug only affects MariaDB itself I'll be in touch with them then.

So the problem itself is that trying to query database with the example you give on mroonga.org and with other query types that work with other engines. As attached (as link, at the end) is the full dataset (I know, it is bit biggie) about 55k rows but the rows are small. If you want smaller set, I can obviously provide it. geotest.sql provides the table structure and geotest.queries.sql provides the queries I've tested.

Quick example of query and explain for it.

```SQL
SELECT id, point_name, ST_Y(coordinates) AS latitude, ST_X(coordinates) AS longitude
FROM locations
WHERE MBRContains(LINESTRING(
    POINT(
        (@lng - @radius / abs(cos(radians(@lat)) * 111.045)),
        (@lat - (@radius / 111.045))),
    POINT(
        (@lng + @radius / abs(cos(radians(@lat)) * 111.045)),
        (@lat + (@radius / 111.045)))
), coordinates);
```
```bash
+------+-------------+-----------+------+---------------+------+---------+------+-------+-------------+
| id   | select_type | table     | type | possible_keys | key  | key_len | ref  | rows  | Extra       |
+------+-------------+-----------+------+---------------+------+---------+------+-------+-------------+
|    1 | SIMPLE      | locations | ALL  | coord_idx     | NULL | NULL    | NULL | 51696 | Using where |
+------+-------------+-----------+------+---------------+------+---------+------+-------+-------------+
1 row in set (0.00 sec)
```

Like said, if this issue lies in MariaDB, I'm following this thread and will issue this to them them if necessary.

https://www.dropbox.com/s/yi1z0f9bjs4mnyw/mroongatest.tar.gz?dl=0

**Comment by kou** [comment]
Thanks for your report.
It's a bug of Mroonga.

We'll fix it. The following patch may fix this bug:

```diff
diff --git a/ha_mroonga.cpp b/ha_mroonga.cpp
index 23bdbe1..fb41701 100644
--- a/ha_mroonga.cpp
+++ b/ha_mroonga.cpp
@@ -2761,7 +2761,7 @@ ulong ha_mroonga::index_flags(uint idx, uint part, bool all_parts) const
     DBUG_RETURN(HA_ONLY_WHOLE_INDEX | HA_KEY_SCAN_NOT_ROR);
   }
   if (mrn_is_geo_key(key)) {
-    DBUG_RETURN(HA_ONLY_WHOLE_INDEX | HA_KEY_SCAN_NOT_ROR);
+    DBUG_RETURN(HA_ONLY_WHOLE_INDEX | HA_KEY_SCAN_NOT_ROR | HA_READ_RANGE);
   }
 
   int error = 0;
```

**Comment by kou** [comment]
I've commit the patch.
