### ISSUE TITLE
SELECT fail after we recreate multiple column index on Windows

### ISSUE THREAD

**Issue by komainu8** [mroonga/mroonga#732]
### What happend?

Ci for Windows fails in multiple_column_index test on wrapper mode as below error.
`ERROR HY000: Can't find FULLTEXT index matching the column list`

See: https://github.com/mroonga/mroonga/actions/runs/9753677738/job/26919336117#step:23:432

### How to reproduce it

We execute mysql-test/mroonga/wrapper/fulltext/multiple_column_index/t/recreate.test on Mroonga with Groonga of main branch for Windows.

```sql
create table diaries (
  id int primary key,
  title varchar(255),
  content text,
  fulltext index (title, content),
  fulltext index (title),
  fulltext index (content)
) default charset utf8mb4 COMMENT = 'engine "innodb"';

insert into diaries values(1, "Hello", "はじめました。");
insert into diaries values(2, "天気", "明日の富士山の天気について");
insert into diaries values(3, "富士山", "今日もきれい。");
select * from diaries where match(title, content) against("富士山");

drop index title on diaries;
create fulltext index new_title_content_index on diaries (title, content);
select * from diaries where match(title, content) against("富士山");
```

### Expected behavior

`select * from diaries where match(title, content) against("富士山");` after recreate multiple column index returns the following result.

```
id	title	content
2	天気	明日の富士山の天気について
3	富士山	今日もきれい。
``` 

### Environment

- OS: Windows
- OS Version: 2019
- DB: MariaDB
- DB Version: 10.11
- Mroonga Version: 14.04
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-version
- libgroonga Version: main
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-libgroonga-version

**Comment by kou** [comment]
https://github.com/groonga/groonga/commit/0857648e766ed97f71861bbb5542724af2d0a8e3 may be related.
