### ISSUE TITLE
mroonga_command says [table][load] name can't start with '_' for a command that works fine on local Groonga

### ISSUE THREAD

**Issue by kk00ss** [mroonga/mroonga#74]
Following commands were tested on local Groonga instance
```sql
SELECT mroonga_command("table_create Bookmarks TABLE_NO_KEY"); 
SELECT mroonga_command("column_create Bookmarks tags COLUMN_VECTOR|WITH_WEIGHT ShortText"); 
SELECT mroonga_command("load --table Bookmarks --input_type json --values [{\"tags\":{\"ruby\":5,\"groonga\":10}}]");```

**Comment by kou** [comment]
Quote is missing in `--values` value in `load`:

```sql
SELECT mroonga_command("load --table Bookmarks --input_type json --values '[{\"tags\":{\"ruby\":5,\"groonga\":10}}]'");
```

Or escape `"`:

```sql
SELECT mroonga_command("load --table Bookmarks --input_type json --values [{\\\"tags\\\":{\\\"ruby\\\":5,\\\"groonga\\\":10}}]");
```

You need to quote or escape value when you use any special character (`"`, `'`, `(`, `)` or space) in value. In this case, you use `"` for `"tags"`.

FYI: `\"` is processed to `"` as MySQL string literal.

**Comment by kk00ss** [comment]
Thank you, I just thought that I can test commands in groonga cmd and they will work with no modifications in mroonga.
