### ISSUE TITLE
'flags "COLUMN_VECTOR|WITH_WEIGHT' yield "16507 The column flag 'WITH_WEIGHT' is invalid. It is ignored"

### ISSUE THREAD

**Issue by kk00ss** [mroonga/mroonga#75]
Hello,
I've already asked this question on Groonga mailing list,
but it seems like I'm getting faster responses here.
Please let me know which way of communication is preferable.

I'm trying to create a table with the following SQL:
CREATE TABLE diaries (
     id INT PRIMARY KEY AUTO_INCREMENT,
     content TEXT COMMENT 'flags "COLUMN_VECTOR|WITH_WEIGHT"',
     FULLTEXT INDEX (content)
     ) ENGINE = Mroonga DEFAULT CHARSET utf8;

and getting following warning : 
"16507 The column flag 'WITH_WEIGHT' is invalid. It is ignored"

I would like to boost _score at indexing time with separate boost value for each term in a document. Probably this functionality is named differently in Mroonga ? 
I'm using Mroonga only because I were unable to find java drivers for Groonga/Dgroonga, could anybody suggest better way of doing this ?

Thanks

**Comment by kou** [comment]
> Please let me know which way of communication is preferable.

You can use which you like!

See answer at https://sourceforge.net/p/groonga/mailman/message/34574837/
