### ISSUE TITLE
Undefined symbol pfs_unlock_mutex_v1 when try to install the mroonga plugin in mariadb 11.4.3

### ISSUE THREAD

**Issue by josepsanzcamp** [mroonga/mroonga#764]
### What happend?

I'm using the latest mroonga source code from the main branch to compile the plugin in debian 12 and mariadb 11.4.3, and when I try to install the plugin, I get the follow error:

```
cat /usr/lib/mysql/plugin/install.sql | mariadb
--------------
INSTALL PLUGIN mroonga SONAME 'ha_mroonga.so'
--------------

ERROR 1126 (HY000) at line 1: Can't open shared library '/usr/lib/mysql/plugin/ha_mroonga.so' (errno: 2, undefined symbol: pfs_unlock_mutex_v1)
```

I'm using the same procedure that I used previously with mariadb 10.11.9.

### How to reproduce it

To compile mariadb 11.4.3, needed to compile the mroonga plugin:

```
apt source mariadb
cd mariadb-11.4.3+maria~deb12
dpkg-buildpackage -rfakeroot -Tbuild
```

To compile the mroonga plugin:

```
git clone git@github.com:mroonga/mroonga.git
cd mroonga
./autogen.sh
./configure \
--with-mysql-source=../mariadb-11.4.3+maria~deb12/ \
--with-mysql-config=../mariadb-11.4.3+maria~deb12/builddir/scripts/mysql_config \
--with-mysql-build=../mariadb-11.4.3+maria~deb12/builddir/
make
```

And to install de mroonga plugin:

```
sudo cp .libs/ha_mroonga.so.0.0.0 /usr/lib/mysql/plugin/ha_mroonga.so
cat data/install.sql data/update.sql | grep -v source | sudo tee /usr/lib/mysql/plugin/install.sql > /dev/null
sudo cp data/uninstall.sql /usr/lib/mysql/plugin/
cat /usr/lib/mysql/plugin/install.sql | mariadb
```

### Expected behavior

The expected result is a correct plugin install

### Environment

- OS: Debian
- OS Version: Debian GNU/Linux 12.7 (bookworm)
- DB: MariaDB
- DB Version: 11.4.3
- Mroonga Version: 14.05
- libgroonga Version: 14.06

**Comment by kou** [comment]
Could you use `cmake` instead of `configure`?
We want to deprecate and remove `configure` support in the future.

If you still need to use `configure`, could you try this?

```diff
diff --git a/lib/Makefile.am b/lib/Makefile.am
index a099eeb9..6680fad3 100644
--- a/lib/Makefile.am
+++ b/lib/Makefile.am
@@ -5,7 +5,7 @@ AM_CPPFLAGS =					\
 	$(GROONGA_CFLAGS)			\
 	$(MYSQL_VERSION_CFLAGS)
 
-libmrn_need_mysql_la_CXXFLAGS = $(AM_CXXFLAGS) $(MYSQL_CFLAGS)
+libmrn_need_mysql_la_CXXFLAGS = $(AM_CXXFLAGS) $(MYSQL_CFLAGS) -DMYSQL_DYNAMIC_PLUGIN
 
 noinst_LTLIBRARIES =				\
 	$(LIBMYSQLSERVICES_COMPAT)		\
```

**Comment by kou** [comment]
> Do you have some documentation about how to use cmake to compile mroonga???

Good question! No... We should update https://mroonga.org/docs/install/others.html#build-from-source before we deprecate/remove `configure` support...

> I'm tried to do the git clone, go to the build dir and execute the cmake .. adding -S and -B params without success.

https://github.com/mroonga/mroonga/blob/main/packages/mariadb-11.4-mroonga/yum/mariadb-11.4-mroonga.spec.in#L74-L78 may help you but we'll update our document eventually...

> As an extra: I have used configure adding the -DMYSQL_DYNAMIC_PLUGIN to the lib/Makefile.am and the compile and install run successfully.

OK. I'll push the change.

**Comment by kou** [comment]
https://mroonga.org/docs/install/others.html#build-from-source will use CMake when we release a new version.
