### ISSUE TITLE
mysql57-community-mroonga installation fails cause auto-generated password

### ISSUE THREAD

**Issue by yoku0825** [mroonga/mroonga#77]
Automated install.sql fails by asking password.

https://github.com/mroonga/mroonga/blob/master/packages/rpm/centos/mysql57-community-mroonga.spec.in#L146

## How to repeat

Enter following commands at fresh CentOS 6.6 box.

```
# rpm -ivh http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm
# rpm -ivh http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
# yum install -y mysql57-community-mroonga
```

And you'll get "Enter password:" prompt (it is in /var/log/mysqld.log)

## Suggested fix

Get auto-generated password in post-script and do *some work* around password expiration..

**Comment by kou** [comment]
Done.
