### ISSUE TITLE
`SELECT` conditions do not apply on `VARBINARY` columns part of an index

### ISSUE THREAD

**Issue by perrinjerome** [mroonga/mroonga#783]
### What happend?

After upgrading our application using mroonga in storage mode with mariadb, from mroonga 13.01 to 14.07, we observed that conditions from the `WHERE` clause of a SQL query from applying to a column of type `VARINARY` that is part of a key does not yield expected results.

### How to reproduce it

I tried to isolate a small reproduction:

```sql
DROP TABLE IF EXISTS `repro`;
CREATE TABLE `repro` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `problematic_column` VARBINARY(100),
  PRIMARY KEY (`uid`, `problematic_column`)
) ENGINE=mroonga;
INSERT INTO `repro` VALUES (1, "hello"), (2, "world");

SELECT problematic_column FROM `repro` WHERE problematic_column = 'hello';
```

### Expected behavior

I expect this last `SELECT` statement to retrieve `'hello`',  but it retrieves nothing. 

With mroonga 13.01 ( and mariadb 10.4.34 ), it retrieves `'hello'`, with mroonga 14.07 ( and mariadb 10.4.34 or mariadb 10.11.8 ), nothing is retrieved.

### Environment

- OS: Debian
- OS Version: 10
- DB: MariaDB
- DB Version: 10.11.8
- Mroonga Version: 14.07
- libgroonga Version: 14.0.7

( mariadb, mroonga and groonga compiled from source )

### Additional context

I understand this is probably a very uncommon case, in most mroonga tables, people are probably using full text indexs, but it seemed good to let you guys know about this. 

PS: one workaround seems to use a `VARCHAR` column instead, like this:

```sql
DROP TABLE IF EXISTS `repro`;
CREATE TABLE `repro` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `problematic_column` VARCHAR(100) BINARY,
  PRIMARY KEY (`uid`, `problematic_column`)
) ENGINE=mroonga;
INSERT INTO `repro` VALUES (1, "hello"), (2, "world");

SELECT problematic_column FROM `repro` WHERE problematic_column = 'hello';
```

/cc @fdiary

**Comment by kou** [comment]
Oh, sorry.
I didn't notice this. This is a bug I introduced in 14.07.

I've fixed this. The next release includes this.

This doesn't break index content. This is just a read problem. So you don't need to reindex `VARBINARY` index with the fix.

**Comment by perrinjerome** [comment]
Thank you very much @kou
