### ISSUE TITLE
1.9 サポートしているプラットフォーム

### ISSUE THREAD

**Issue by hiroyuki-sato** [mroonga/mroonga#81]
> [1.9 サポートしているプラットフォーム.](http://mroonga.org/ja/docs/characteristic.html#supported-platforms)
> * Linux x86_64 (Intel64/AMD64)

となっていますが、OSXとWindowsも現在は動作しますよね？

**Comment by kou** [comment]
はい！動作します！

**Comment by myokoym** [comment]
サポート対象が増えるたびに追記するのは大変そうなので、「サポートしているプラットフォームは[2. インストール](http://mroonga.org/ja/docs/install.html)を参照してください」のように書いておくのはどうでしょうか。

**Comment by kou** [comment]
いいと思います！

**Comment by myokoym** [comment]
ありがとうございます！そのように修正しておきます。

**Comment by myokoym** [comment]
1ec03bc043291f58caa36a126591df6e4192d733 で修正しました。
