### ISSUE TITLE
Crash 5.09

### ISSUE THREAD

**Issue by Codeusa** [mroonga/mroonga#82]
I have a fairly large table with 7 million rows, since upgrading to 5.09 mysql randomly shuts off, event viewer claims this is the reason

I am using  Mroonga x64 package on windows, there is no error present in the logs of mysql or groonga 

Faulting application name: mysqld.exe, version: 10.1.8.0, time stamp: 0x56338be9
Faulting module name: groonga.dll, version: 0.0.0.0, time stamp: 0x56338ac6
Exception code: 0xc0000409
Fault offset: 0x00000000001f5c63
Faulting process id: 0xd10
Faulting application start time: 0x01d1230476153722
Faulting application path: C:\xampp\mysql\bin\mysqld.exe
Faulting module path: C:\xampp\mysql\bin\groonga.dll
Report Id: f9b09e93-8efc-11e5-9401-002590687ff9
Faulting package full name: 
Faulting package-relative application ID:

**Comment by kou** [comment]
Could you show `groonga.log` and `mysqld.log`? They exist in MySQL data folder.

**Comment by Codeusa** [comment]
https://paste.ee/p/V0y1b#CqTHETT5aZKNVAXGKFbuUM8r5T0DEVwv

https://paste.ee/p/GxRRB#qn5g50DLpTyZu22mkedQZGVv5LqsQsfx


My log files

**Comment by kou** [comment]
Thanks.
I'm sorry but I couldn't find any useful information.

Are you using any UDF provided by Mroonga such `mroonga_snippet`?

**Comment by Codeusa** [comment]
I am not, however the crash only occurs on the large table that has a Mroonga engine, the crash seems random but it has to do with the large amount of queries it receives, as Windows states it is groonga.dll that is actually erroring. However there is no error generated. 

If you wish I can provide you a copy of the table for you to test.

**Comment by kou** [comment]
> Also this is in the log

It's helpful. You need to increase virtual memory for treating large data on Windows.

See http://windows.microsoft.com/en-us/windows/change-virtual-memory-size for how to increase virtual memory.

**Comment by Codeusa** [comment]
Sadly, this did not resolve the issue, i switched to x64 and the issue still persist.

**Comment by kou** [comment]
Could you show size of your database folder and how many virtual memory is increased?

**Comment by kenhys** [comment]
This issue is not active anymore. I'll close it.
