### ISSUE TITLE
Question about how Mroonga Scoring 

### ISSUE THREAD

**Issue by idontgotit** [mroonga/mroonga#83]
Hi, im newbie and trying use mroonga, But i dont know how mroonga score in link :http://mroonga.org/docs/reference/full_text_search/scoring.html

Can you explain me please ?

The first
2^20 is ?? Maybe 2 is number token , and 20 is what?
The Second
Same issue , denominator "8" and "9" is what? I dont know what relation about correct answer 2,3 with 8,9
Can you please expalin to me exactly what mroonga doing ?

Thanks for your help

**Comment by kou** [comment]
> The first
> 2^20 is ?? Maybe 2 is number token , and 20 is what?

They are meaningless. We just use `1048576` as the number of tokens in all documents. We should use more strict value for the number of tokens in all documents instead of `1048576`. But computing strict value isn't light operation. So we just use `1048576` as the number of tokens in all documents.

> The Second
> Same issue , denominator "8" and "9" is what? I dont know what relation about correct answer 2,3 with 8,9

They are estimated values. Estimation is more light operation than computing strict value. But estimation may return wrong value.

BYW, I recommend you that you use `MATCH() AGAINST('*D+ ...' IN BOOLEAN MODE)` such as `MATCH(body) AGAINST('*D+ keyword1 keyword2' IN BOOLEAN MDOE` instead of `MATCH() AGAINST('...' IN NATURAL LANGUAGE MODE)` (it's the default in MySQL). Because you can use Web search engine (such as Google) like query language in `IN BOOLEAN MODE`.

Mroonga uses TF (Term Frequnency) as score in `IN BOOLEAN MODE`.

**Comment by idontgotit** [comment]
Thanks you :) 
Can you answer me one more question please ?

I tried use Full text search mroonga, it perfect with one field. 
My issue is now i want search in 2 field .
Example : i search with value :  にゅーでじたるけーぶる IN BOOLEAN MODE.
in one table, i have 2 field  "name" and "furigana".
2 result (search in "name" and "furigana")maybe same or different , i dont know mroonga can find what is duplicate or not ?
if mroonga can do it , how i can add score duplicate ?
Example : i search in "name" , result is 
name                               Furigana
ニューデジタルケーブル  , にゅーでじたるけーぶる
and search in furigana , result is : 
name                                Furigana
ニューデジタルケーブル, にゅーでじたるけーぶる

Thanks for your help

**Comment by kou** [comment]
Could you show us SQL (`CREATE TABLE`, `INSERT` and `SELECT`) what you use?

**Comment by idontgotit** [comment]
here is SQL i use 

CREATE TABLE IF NOT EXISTS `company_mst` (
  `com_company_code` varchar(10) NOT NULL,
  `com_company_name` varchar(128) DEFAULT NULL,
  `com_company_furigana` varchar(128) DEFAULT NULL,
  FULLTEXT KEY `com_company_name` (`com_company_name`)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE FULLTEXT INDEX com_company_furigana ON company_mst(com_company_furigana);


INSERT INTO `company_mst` ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる'),



SELECT * FROM company_mst WHERE MATCH (com_company_name) AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
ORDER BY MATCH (com_company_name) AGAINST ("にゅーでじたるけーぶる") DESC;

SELECT * FROM company_mst WHERE MATCH (com_company_furigana) AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
ORDER BY MATCH (com_company_furigana) AGAINST ("にゅーでじたるけーぶる") DESC;

**Comment by kou** [comment]
Thanks. Use multicolumn index:

```sql
CREATE TABLE IF NOT EXISTS company_mst (
com_company_code varchar(10) NOT NULL,
com_company_name varchar(128) DEFAULT NULL,
com_company_furigana varchar(128) DEFAULT NULL,
FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE) DESC;
```

**Comment by idontgotit** [comment]
i tried 
SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE) DESC;

But it returned an empty result set.

If i remove "com_company_name" or "com_company_furigana" it success ..

**Comment by kou** [comment]
Really? It works well on my environment with the following SQL:

```sql
CREATE TABLE IF NOT EXISTS company_mst (
  com_company_code varchar(10) NOT NULL,
  com_company_name varchar(128) DEFAULT NULL,
  com_company_furigana varchar(128) DEFAULT NULL,
  FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO company_mst VALUES ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる');

SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE) DESC;
```

Here is a transcript:

```text
% mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.5.43-debug-log Source distribution

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database x;
Query OK, 1 row affected (0.00 sec)

mysql> use x;
Database changed
mysql> set names utf8;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE IF NOT EXISTS company_mst (
    ->   com_company_code varchar(10) NOT NULL,
    ->   com_company_name varchar(128) DEFAULT NULL,
    ->   com_company_furigana varchar(128) DEFAULT NULL,
    ->   FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana)
    -> ) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
Query OK, 0 rows affected (0.11 sec)

mysql> INSERT INTO company_mst VALUES ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる');
Query OK, 1 row affected (0.06 sec)

mysql> SELECT * FROM company_mst
    ->   WHERE MATCH (com_company_name, com_company_furigana)
    ->         AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
    ->   ORDER BY
    ->         MATCH (com_company_name, com_company_furigana)
    ->         AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE) DESC;
+------------------+-----------------------------------+-----------------------------------+
| com_company_code | com_company_name                  | com_company_furigana              |
+------------------+-----------------------------------+-----------------------------------+
| 4800000682       | ニューデジタルケーブル | にゅーでじたるけーぶる |
+------------------+-----------------------------------+-----------------------------------+
1 row in set (0.00 sec)
```

I don't help you without you provide what you did as is.

**Comment by idontgotit** [comment]
thanks you very much :)

Maybe i wrong in somewhere, i drop database and create again, it working fine .

And I have few question , can you answer it please ?
The first
I curious about we need or not create one more fulltext index ?
like this:
CREATE FULLTEXT INDEX com_company_furigana ON company_mst(com_company_furigana);

or only one fulltext index when create table is enough ??

Second
I saw your command, value "にゅーでじたるけーぶる" , it exists in 2 field .
if now i have one more field is : com_url , example is "http://av.watch.impress.co.jp/"

My DB now is 

CREATE TABLE IF NOT EXISTS company_mst (
  com_company_code varchar(10) NOT NULL,
  com_company_name varchar(128) DEFAULT NULL,
  com_company_furigana varchar(128) DEFAULT NULL,
  com_url varchar(128) DEFAULT NULL,
  FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO company_mst ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://av.watch.impress.co.jp/')

How i can search with url,name, furigana in one time?
Example is search 2 value "'http://av.watch.impress.co.jp/" and "にゅーでじたるけーぶる" ,it will show one result is  4800000682  | ニューデジタルケーブル | にゅーでじたるけーぶる | 'http://av.watch.impress.co.jp


Thanks for your help

**Comment by kou** [comment]
Could you create one issue for one question? I want to close this issue because this issue is for score.

**Comment by idontgotit** [comment]
ok, i will create it in new issue

**Comment by kou** [comment]
Thanks.
