### ISSUE TITLE
How to search with 2 value in one time  Mroonga

### ISSUE THREAD

**Issue by idontgotit** [mroonga/mroonga#84]
I have few question about Mroonga, can you answer it please ?

The first
I curious about we need create only one or more fulltext index ?
like this:
CREATE FULLTEXT INDEX com_company_furigana ON company_mst(com_company_furigana);

or only one fulltext index when create table is enough ??

Second

i have DB  is

CREATE TABLE IF NOT EXISTS company_mst (
com_company_code varchar(10) NOT NULL,
com_company_name varchar(128) DEFAULT NULL,
com_company_furigana varchar(128) DEFAULT NULL,
com_url varchar(128) DEFAULT NULL,
FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO company_mst ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://av.watch.impress.co.jp/')

Have any way search with url,name, furigana in one time,add score if result duplicate?

Example is search 2 value "'http://av.watch.impress.co.jp/" and "にゅーでじたるけーぶる" . Search Url in field "Com_url" and value "にゅーでじたるけーぶる"  in both field name and furigana .
It will show one result is 4800000682 | ニューデジタルケーブル | にゅーでじたるけーぶる | http://av.watch.impress.co.jp

**Comment by kou** [comment]
> The first
> I curious about we need create only one or more fulltext index ?
> like this:
> CREATE FULLTEXT INDEX com_company_furigana ON company_mst(com_company_furigana);
> 
> or only one fulltext index when create table is enough ??

If you want to search all columns in one time, you need to create only one fulltext index as multicolumn fulltext index.

If you don't want to search all columns in one time, you can create multiple fulltext indexes.

> Second

Could you show `SELECT` what you used and the expected result?

**Comment by idontgotit** [comment]
this is select command
SELECT * FROM company_mst WHERE MATCH (com_url) AGAINST ("http://www.newdc.co.jp" IN BOOLEAN MODE)

SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana)
        AGAINST ("にゅーでじたるけーぶる" IN BOOLEAN MODE) DESC;

each command can have other result, it maybe duplicate. I want result duplicate auto add score.
In my example, i have INSERT like this 
INSERT INTO company_mst('0300000007', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる', 'http://www.newdc.co.jp')
INSERT INTO company_mst ('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://av.watch.impress.co.jp/')
INSERT INTO company_mst('0100000237', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://www.newdc.co.jp')


Expected result is 0300000007 and 0100000237 in top. and  4800000682 behind.
Thanks you

**Comment by kou** [comment]
Thanks for providing SQL, actual result and expected results.

Put `com_url` to your multicolumn fulltext index and use `*D+ にゅーでじたるけーぶる OR http://www.newdc.co.jp` as query:

```sql
CREATE TABLE IF NOT EXISTS company_mst (
  com_company_code varchar(10) NOT NULL,
  com_company_name varchar(128) DEFAULT NULL,
  com_company_furigana varchar(128) DEFAULT NULL,
  com_url varchar(128) DEFAULT NULL,
  FULLTEXT KEY (com_company_name, com_company_furigana, com_url)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO company_mst VALUES('0300000007', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる', 'http://www.newdc.co.jp');
INSERT INTO company_mst VALUES('4800000682', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://av.watch.impress.co.jp/');
INSERT INTO company_mst VALUES('0100000237', 'ニューデジタルケーブル', 'にゅーでじたるけーぶる','http://www.newdc.co.jp');

SELECT * FROM company_mst
  WHERE MATCH (com_url) AGAINST ("http://www.newdc.co.jp" IN BOOLEAN MODE);

SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*D+ にゅーでじたるけーぶる OR http://www.newdc.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*D+ にゅーでじたるけーぶる OR http://www.newdc.co.jp" IN BOOLEAN MODE) DESC;
-- com_company_code	com_company_name	com_company_furigana	com_url
-- 0300000007	ニューデジタルケーブル	にゅーでじたるけーぶる	http://www.newdc.co.jp
-- 0100000237	ニューデジタルケーブル	にゅーでじたるけーぶる	http://www.newdc.co.jp
-- 4800000682	ニューデジタルケーブル	にゅーでじたるけーぶる	http://av.watch.impress.co.jp/
```

See http://mroonga.org/docs/reference/full_text_search/boolean_mode.html about `*D+`.

**Comment by idontgotit** [comment]
Thanks you very much. It working fine :)
