### ISSUE TITLE
Question about how to use weight 

### ISSUE THREAD

**Issue by idontgotit** [mroonga/mroonga#86]
Hi, Its me again :)
I have question about how to use *W custom weight in mroonga
i read in this
 http://mroonga.org/docs/reference/full_text_search/boolean_mode.html#w-pragma
and found "W pragma" maybe can use . I tried but not success.
Can you help me please ?
This is my database

```sql
CREATE TABLE IF NOT EXISTS `company_mst` (
  `com_company_code` varchar(10) NOT NULL primary key,
  `com_company_name` varchar(128) DEFAULT NULL,
  `com_company_furigana` varchar(128) DEFAULT NULL,
  `com_url` text
  FULLTEXT KEY com_company_name_and_furigana (com_company_name, com_company_furigana),
  FULLTEXT KEY (com_company_name, com_company_furigana, com_url),
  FULLTEXT KEY (com_url)
) ENGINE=Mroonga DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 
```

I tried insert

```sql
INSERT INTO company_mst VALUES ('0600000075',  '和光電機通信工業', 'わこう','')
INSERT INTO company_mst VALUES ('4800000900', 'ワタシハ二本ゴガナセマス', 'ワタシハ二本ゴガナセマス', 'http://www.wako-denki.co.jp')
```
My SQL 

```sql
 SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST (" *D+ 和光電機通信工業 OR   http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST (" *D+ 和光電機通信工業 OR  http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC;
```

My result is 0600000075 before  4800000900

Now i want change Weight com_url , i want it always higher than anyone. How to do it ?
My expected with example is 4800000900 before 0600000075

Thanks for your help
p/s: Have anyway change  normalize mroonga to anything else ?

**Comment by kou** [comment]
Could you also show `SELECT` with `W` pragma what you tried?

**Comment by kou** [comment]
The following `SELECT` may be a `SELECT` what you want.

```sql
SELECT *,
       MATCH (com_company_name, com_company_furigana, com_url)
       AGAINST ("*D+W1:1,2:1,3:10 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
   FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*D+W1:1,2:1,3:10 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*D+W1:1,2:1,3:10 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC;
```

**Comment by idontgotit** [comment]
thanks .  i tried 

 SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR   http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST (" *W1:1,2:1,3:10 *D+ 和光電機通信工業 OR  http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC;

it have any different about your suggest ?

**Comment by kou** [comment]
Could you show the actual result and the expected result?

**Comment by kou** [comment]
FYI1: You can't put any characters include spaces before pragma such as `"*W..."`.

FYI2: Multiple pagram syntax is `"*${PRAGMA1}${PRAGMA2}${...}"` not `"*${PRAGMA1} *${PRAGMA2} ...`.

**Comment by idontgotit** [comment]
i tried 
SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR   http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR  http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC

dont have spaces. Sr wrong .

And here my result
![screenshot from 2015-12-01 12 32 40](https://cloud.githubusercontent.com/assets/12474525/11493117/c016b22a-9827-11e5-98a9-e7393103d0fb.png)

**Comment by kou** [comment]
Thanks for providing actual result.
Could you also provide expected result?

**Comment by idontgotit** [comment]
my result in last post is expected result.
im curious about what different my sql i tried with your suggest?

**Comment by kou** [comment]
Your SQL means `*D+` or `和光電機通信工業` or `http://www.wako-denki.co.jp`. `*D+` is treated as one keyword not pragma.

**Comment by idontgotit** [comment]
that mean it dont have effect add score if result duplicated in more field ?

**Comment by kou** [comment]
I'm sorry but I couldn't understand what you want to know...
Could you show sample data and SQL with question?

**Comment by idontgotit** [comment]
i tried 
SELECT * FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR   http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR  http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC

And you said 

Your SQL means *D+ or 和光電機通信工業 or http://www.wako-denki.co.jp. *D+ is treated as one keyword not pragma.

I want know what action  *D+  work in my SQL ? It have or not add score if result duplicate with *W set weight ?
Example
i have database with field like this:
INSERT INTO company_mst VALUES ('4800000900', 'ワタシハ二本ゴガナセマス', 'ワタシハ二本ゴガナセマス', 'http://www.wako-denki.co.jp')
INSERT INTO company_mst VALUES ('4800000901', 'ワタシハ二本ゴガナセマス', '', 'http://www.wako-denki.co.jp')

i want 4800000900 higher score than 4800000901. Because "ワタシハ二本ゴガナセマス" apear two time . And i think *D+ can add score in this case.
In SQL I tried , it can work or not?

**Comment by kou** [comment]
Thanks.

First, you should add `MATCH() AGAINST()` to column list like the following to confirm score:

```sql
SELECT *, MATCH(...) AGAINST(...)
  FROM ...
  WHERE ...;
```

In this case:

```sql
SELECT com_company_code,
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
   FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
  ORDER BY
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE) DESC;
```

returns:

```text
4800000900	10
4800000901	10
```

Both of them have the same score.

> Because "ワタシハ二本ゴガナセマス" apear two time . And i think *D+ can add score in this case.

I couldn't understand why "ワタシハ二本ゴガナセマス" is related to score. Your query doesn't include "ワタシハ二本ゴガナセマス".

It seems that you misunderstand D pragma. Read document again: http://mroonga.org/docs/reference/full_text_search/boolean_mode.html#d-pragma

You can find difference with this data:

```sql
INSERT INTO company_mst VALUES ('4800000900', '和光電機通信工業', '*D+', '');
INSERT INTO company_mst VALUES ('4800000901', '和光電機通信工業', '', '');
```

Your query:

```sql
SELECT com_company_code,
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
   FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10 *D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE);
```

returns:

```text
4800000900	2
4800000901	1
```

`4800000900` has score 2 because `*D+` is treated as query not pragma.

My suggestion query:

```sql
SELECT com_company_code,
        MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE)
   FROM company_mst
  WHERE MATCH (com_company_name, com_company_furigana, com_url)
        AGAINST ("*W1:1,2:1,3:10D+ 和光電機通信工業 OR http://www.wako-denki.co.jp" IN BOOLEAN MODE);
```

returns:

```text
4800000900	1
4800000901	1
```

`4800000900` has score 1 because `*D+` is NOT treated as query. It's pragma.

**Comment by idontgotit** [comment]
Thanks, i will try it later.
Thanks for your help :)
