### ISSUE TITLE
Support MariaDB release for CentOS 7.2

### ISSUE THREAD

**Issue by relip** [mroonga/mroonga#91]
Currently the installation requires exact MariaDB __5.5.44_1__ and it is the most recent release on CentOS 7.1, however on CentOS 7.2, __5.5.44_2__ is the most recent one, so I had to downgrade mariadb version to 44_1.

Maybe changing _exact_ version requirements to _gte(>=)_ will make it flexible? If there are no problems of course.

**Comment by kou** [comment]
Thanks for your report. I've rebuild Mroonga package for MariaDB 5.5.44_2.

> Maybe changing exact version requirements to `gte(>=)` will make it flexible? If there are no problems of course.

It causes a problem. MySQL/MariaDB reports error on loading Mroonga when running MySQL/MariaDB version and MySQL/MariaDB version built for Mroonga are different.

**Comment by relip** [comment]
Ah, okay. Thanks!
