### ISSUE TITLE
Storage-mode with UNIQUE constraint returns incorrect ER_DUP_ENTRY

### ISSUE THREAD

**Issue by yoku0825** [mroonga/mroonga#99]
## Description

* Storage-mode Mroonga which has UNIQUE constraint returns ER_DUP_ENTRY(Duplicate entry %d for key %s), even that record had already been removed.

## Reproducible environment

* MySQL 5.6.29 + Mroonga 6.00(mysql-community-mroonga)
* MySQL 5.7.11 + Mroonga 6.00(mysql57-community-mroonga)
* MySQL 5.6.28 + Mroonga 5.12(mysql-community-mroonga)

## How to repeat

```
mysql> CREATE TABLE t1 (num int, UNIQUE KEY (num)) Engine = Mroonga;
Query OK, 0 rows affected (0.08 sec)

mysql> INSERT INTO t1 VALUES (1);
Query OK, 1 row affected (0.03 sec)

mysql> DELETE FROM t1;
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (1);
ERROR 1062 (23000): Duplicate entry '1' for key 'num'
```

**Comment by kou** [comment]
Thanks for your report!
I've fixed it.
